bazelbuild/buildtools

- WORKSPACE
- buildifier/buildifier.go
Also add a workspace name and some formatting to the README.
> Remove -a from usage

- core/print_test.go
this unblocks unforking with Google internal.
> defer acquisition of testpath

- core/parse.y
- core/testdata/045.golden
- core/testdata/045.in
> Fix bug where 'x = a if cond else b' was incorrectly parsed

- README.md
- core/BUILD
- core/build_defs.bzl
- core/parse.y.go
Satisfy https://github.com/bazelbuild/buildifier/issues/16 and
https://github.com/bazelbuild/buildifier/issues/14 by checking in
parse.y.go
> Check in parse.y.go, and add test to ensure freshness

- wspace/BUILD
- wspace/workspace.go
- wspace/workspace_test.go
> add a method to find the bazel-root by looking up for a WORKSPACE file

- buildifier/BUILD
> Set buildifier:buildifier to //visibility:public

- buildozer/main.go
was returning [] instead of [] for empty input, causing buildozer to do nothing
> bug fix for stringList

- edit/buildozer.go
This is intended to fix issue #55. It's the first time I've written Go, so I'm sorry if it's not up to snuff.
> Add BUILD.bazel & BUCK as valid BUILD file names. (#55)

- edit/buildozer.go
> buildozer: print arbitrary Exprs with build.FormatString

- buildozer/README.md
Added README.md to buildozer. Haven't worked on it much, and it's mostly a compilation of comments and descriptions already in the code. @pmbethe09
> Buildozer Readme

- BUILD.bazel
- README.md
- build/BUILD.bazel
- build/rewrite.go
- buildifier/buildifier.go
- buildozer/README.md
- buildozer/main.go
- edit/buildozer.go
- edit/edit.go
- edit/edit_test.go
- edit/fix.go
- edit/types.go
- generatetables/generate_tables.go
- lang/tables.gen.go
- unused_deps/unused_deps.go
Change generated with:
```bash
grep -rl bazelbuild/buildifier . | xargs -I {} sed -i 's/bazelbuild\/buildifier/bazelbuild\/buildtools/g' {}
```
> Finish renaming bazelbuild/buildifier to bazelbuild/buildtools.

- build/lex.go
- build/print.go
- build/testdata/027.golden
- build/testdata/031.in
- build/testdata/046.golden
- build/testdata/046.in
Fixes #68. #70 seems to also be fixed by this.
> Fix disappearing comments

- build/lex.go
- build/parse.y
- build/parse.y.go
- build/print.go
- build/syntax.go
- build/testdata/047.golden
- build/testdata/047.in
- build/walk.go
> Allow list comprehensions contain conditions after each for expression

- WORKSPACE
> Use new mirror.bazel.build hostname

- edit/buildozer.go
> Command 'replace' works on string attributes

- build/BUILD.bazel
See: https://github.com/kubernetes/test-infra/pull/4859#issuecomment-347749178 for more context.
Related: https://github.com/bazelbuild/buildtools/issues/14
> Make Gazelle happy with the checked in generated code.

- build/print_test.go
- build/rewrite.go
- build/testdata/050.golden
- build/testdata/050.in
- build/testdata/050.stripslashes.golden
- tables/jsonparser.go
- tables/tables.go
Also shorten //foo:foo to :foo within foo/BUILD
> Allow tables.json to configure shortening //foo:bar to :bar within foo/BUILD

- wspace/workspace.go
Pants uses the existence of an executable file named pants to detect its workspace root.
> Detect pants workspace

- buildozer/BUILD.bazel
b96ccf42ea08b35c66137000e7e9fee1bb338450 added an import but not a dep
> Fix BUILD file for buildozer

- buildifier/buildifier.go
This prints the newly formatted file if there are changes to apply, or
prints nothing if there are no changes to apply.
It only takes one file.
This is useful for Phabricator's linter infrastructure, because they
require a replacement text, rather than a patch.
Without this change, Phabricator users need to read BUILD files
manually, pipe them into buildifier's stdin, and manually diff the two
to check whether changes need applying. The new mode makes this process
a lot cleaner.
> Add print_if_changed mode to buildifier

- .gitignore
These are files created by IntelliJ IDEA to define project modules.
> Add .iml files to .gitignore

- build/print_test.go
Currently only test cases with a `.formatbzl.golden` file are tested with `--format_bzl`.
With this change all test cases are tested with and without the `--format_bzl` flag. If there's no special `.formatbzl.golden` file, the `.golden` file is used in both cases.
Idempotence tests are also run with and without the flag. If there's a `.formatbzl.golden` counterpart for a given `.golden` file, this file is not tested for idempotence with the flag. The opposite is not true: `.format.golden` files are tested for idempotence with and without the flag.
> Update the test suite to run all tests separately with --format_bzl

- buildozer/BUILD.bazel
- generatetables/BUILD.bazel
- unused_deps/BUILD.bazel
> Use `embed` instead of `library` in go_binary

- build/lex.go
- build/print.go
- build/testdata/052.golden
- build/testdata/052.in
> Support integer division operator (//)

- .bazelci/presubmit.yml
- README.md
> update to new bazel ci

- build/lex.go
- build/parse.y
- build/parse.y.go
- build/parse_test.go
- build/print.go
- build/rewrite.go
- build/rule.go
- build/rule_test.go
- build/syntax.go
- edit/buildozer.go
- edit/edit.go
- edit/fix.go
Reverts #219
This reverts commit d0f4e566e2b807ac978d89c58a65c79b0b39ffe5.
> Revert "Introduce "Ident" node, to distinguish between numbers and idents. (#219)"

- build/lex.go
- build/parse.y
- build/parse.y.go
- build/print.go
- build/syntax.go
- build/testdata/051.golden
- build/testdata/051.in
If-elif-else nodes are represented in the AST according to the Skylark-in-Go parser (https://github.com/google/skylark/blob/master/syntax/syntax.go), as a chain of nested if-else statements.
> Refactor if-else nodes

- build/parse.y
- build/parse.y.go
- build/syntax.go
This information is not used. The pretty-printer will decide whether
there should be a comma or not.
> Remove information about trailing comma

- build/lex.go
- build/parse.y
- build/parse.y.go
- build/print.go
- build/syntax.go
- build/walk.go
Def and For nodes are represented in the AST like in the Skylark-in-Go parser (https://github.com/google/skylark/blob/master/syntax/syntax.go).
> Refactor def and for statements nodes

- buildifier/BUILD.bazel
- buildifier/buildifier.go
- buildifier/integration_test.sh
The mode is probably supposed to be default in the future, but not now yet.
> Add a mode to detect the formatting mode automatically based on the filename

- buildifier/buildifier.go
- buildifier/integration_test.sh
- differ/diff.go
Fixes https://github.com/bazelbuild/buildtools/issues/221
exit 4 if fix or diff mode detects a change.
> exit non-zero in mode fix/diff when work is required.

- build/rule.go
- build/rule_test.go
> Ensure nested calls aren't treated as rules.

- BUILD.bazel
- WORKSPACE
- buildifier/BUILD.bazel
- buildifier/README.md
- buildifier/def.bzl
- buildifier/deps.bzl
- buildifier/runner.bash.template
> Rule to conveniently use buildifier via Bazel

- edit/edit.go
- edit/edit_test.go
Add DictionaryDelete method for removing a key/value pair of a dictionary attribute.
> Add DictionaryDelete method

- build/lex.go
The skipStmt was used in the old verison of buildifier to search for the end of `PythonBlock` nodes. After the `PythonBlock` nodes had been removed, it was still used to detect whether the parser was inside of a statement. That is bad in terms of performance (the method is looking at the input ahead making the scan time non-linear), also it's not necessary, the information whether the parser is currently inside of a statement can be exctracted from `in.depth` (the current depth of `(`, `[`, `{`) and `in.cleanLine` (whether the current line is clean or the cursor is positioned after some non-space characters).
> Remove the outdated skipStmt method

- edit/edit.go
- edit/edit_test.go
https://docs.bazel.build/versions/master/skylark/build-style.html#file-structure
> Fix PackageDeclaration() - package() is added after load() statements.

- edit/buildozer.go
> Remove targetting package rules implicitly

- WARNINGS.md
This file will be referred from the warnings buildifier's linter will generate.
> Document buildifier warnings

- WORKSPACE
- api_proto/api.gen.pb.go
- build/parse.y.go
Needed as part of bazelbuild/bazel#6283.
> Update rules_go to 0.16.0

- warn/warn.go
> Refactor the code

- WARNINGS.md
- build/print.go
- edit/edit.go
- warn/warn.go
- warn/warn_bazel.go
- warn/warn_bazel_test.go
Namely `git_repository`, `new_git_repository`, and `http_archive`.
> Provide warnings and fixes for removed native functions

- buildifier/buildifier.go
- warn/warn.go
`buildfier --lint=warn --warnings=foo,bar ...`
> Allow defining a list of warnings

- unused_deps/unused_deps.go
This works around the following changes to params files:
https://groups.google.com/d/topic/bazel-discuss/oMguVWL-Ckg/discussion
The fix uses an apsect to extra the argument list of JavaBuilder
actions, instead of relying on params files being available at
well-known locations.
See #396
> Fix unused_deps' params file handling

- buildifier/buildifier.go
Commit 41d89cd7c8328bb912f3b8f50d2dc970805d21f8 breaks https://github.com/brown/bazel-mode
and acts differently from how the diff utility works.
The diff command does not output file name information when you diff two files, since it's clear what
files the diff output applies to.  buildifier should do the same.  If you only specify one file and -mode=diff,
it should not output file name info, just the diffs.
> Only display file names for -mode=diff when there is more than one file.

- buildifier/buildifier.go
Variable main.diff was not set, so running with "-mode=diff" would panic.
> Fix bug in commit 56771622e.

- warn/warn_control_flow.go
- warn/warn_control_flow_test.go
Fixes #549
Workaround for #550: the check is temporarily disabled for comprehensions.
> Fix wrong unitialized warnings

- WARNINGS.md
- buildifier/README.md
> Update the documentation about default warnings

- build/syntax.go
- buildifier/utils/flags.go
Fix a couple of comments with typos.
> Fix comments

- buildifier/BUILD.bazel
- buildifier/integration_test.sh
Fixes https://github.com/bazelbuild/buildtools/issues/621
> Windows: fix sh_test to use Bash runfiles library

- warn/warn.go
Make a local copy of a list shared among multiple threads before sorting it.
> Fix race condition

- buildifier/def.bzl
This was removed in 3c231fc339c96382348e1711f461e6fbf243e0fd
> Remove showlog from bzl

- edit/buildozer.go
* Set the minimum amount of arguments to `set` and `set_if_absent` to 1 (was 2).
* Exit prematurely if there are not enough or too many arguments (was: warn and continue the execution)
* If `set` or `set_if_absent` are called without a value provided, set it to an empty list if a list was expected, on `None` otherwise (was: empty list or crash with runtime error).
Fixes #616
> Allow setting empty arguments

- WARNINGS.md
- warn/warn.go
- warn/warn_bazel.go
- warn/warn_bazel_test.go
> Implement a warning for the print function

- warn/warn.go
- warn/warn_bazel.go
- warn/warn_bazel_test.go
This is the first CL in a series, the rest will be submitted separately.
> Update warning functions in bazel_warn.go to the new signature

- build/print.go
- warn/warn.go
- warn/warn_control_flow.go
The updated signature will allow making atomic automatic suggestions.
> Refactor warnings in warn_control_flow.go

- WARNINGS.md
- warn/warn.go
- warn/warn_bazel_operation.go
- warn/warn_bazel_operation_test.go
> Provide a warning for overly nested depsets

- edit/buildozer.go
- edit/edit.go
- edit/edit_test.go
> Buildozer support for select add/remove

- edit/edit.go
Fix a potential NPE in `AddValueToList`.
> Fix AddValueToList

- buildozer/README.md
It seems like new is the right command for this and new_rule doesn't
exist
> Update new_rule doc to new

- warn/warn.go
- warn/warn_bazel_api.go
> Make the bzl-visibility check non-default

- edit/buildozer.go
- edit/buildozer_test.go
> Fix recursive traversal of BUILD files for "..." targets

- warn/warn.go
- warn/warn_bazel.go
- warn/warn_bazel_api.go
- warn/warn_bazel_test.go
> Don't run rule warnings functions on WORKSPACE files

- WARNINGS.md
- warn/warn.go
- warn/warn_operation.go
- warn/warn_operation_test.go
Warn about and fix single-element list concatenations.
> Implement list-append warning and fix

- warn/warn_docstring.go
- warn/warn_docstring_test.go
> Don't warn about undocumented *

- WORKSPACE
- buildozer/npm/.gitignore
- buildozer/npm/BUILD.bazel
- buildozer/npm/index.ts
- buildozer/npm/package-lock.json
- buildozer/npm/package.json
/cc @kwonoj this is to support automating the ts project references -> BUILD file translation
> add nodejs binding to conveniently use buildozer from a node program

- buildifier/BUILD.bazel
- buildifier/npm/BUILD.bazel
- buildifier/npm/test.js
- buildozer/BUILD.bazel
- buildozer/npm/BUILD.bazel
- buildozer/npm/test.js
@vladmos I'll add the missing testing to this PR as well. Just wanted to get it here quickly in case you want to merge and re-release now before the tests are ready.
> Fix missing files in npm distribution

- buildozer/buildozer_test.sh
- edit/buildozer.go
> Allow quoted arguments in buildozer's replace command

- edit/buildozer.go
Some organizations contain BUILD file templates or other files that resemble BUILD files. It's useful to be able to use buildifier to modify those variables. This PR simply exports the BUILD file name variables so that libraries can tweak these. This isn't an ideal solution, but would unblock many use cases without users needing to maintain custom patches.
> Export build file names variables

- build/syntax.go
- edit/buildozer.go
Golint complains if exported method don't have comments, added them.
> Add comments for golint

- buildifier/utils/flags.go
> Fix a typo

- build/build_defs.bzl
- buildifier/def.bzl
- buildifier/deps.bzl
- buildifier/npm/BUILD.bazel
- buildozer/npm/BUILD.bazel
- lang/defs.bzl
Required for enabling buildifier checks on this repository.
> Address linter warnings

- buildifier/utils/utils.go
- buildifier/utils/utils_test.go
This appears to be a common-enough file extension for Starlark code.
See for example:
https://github.com/google/starlark-go/tree/master/starlark/testdata
> Have .star files detected as Starlark

- buildozer/README.md
- buildozer/buildozer_test.sh
- edit/buildozer.go
> buildozer: return 0 if only readonly commands have been executed

- warn/warn.go
Export the function so that it can be reused from other modules.
> Export HasDisablingComment

- buildifier/utils/utils.go
> Handle file traversal errors correctly

- buildozer/README.md
- buildozer/buildozer_test.sh
- edit/buildozer.go
> Support comments in command files

- buildifier/README.md
> Update the documentation

- build/rewrite.go
- build/testdata/007.build.golden
- build/testdata/007.bzl.golden
- build/testdata/007.in
- tables/jsonparser.go
- tables/jsonparser_test.go
- tables/tables.go
- tables/testdata/simple_tables.json
Replace blacklist/whitelist with denylist/allowlist.
> Respectful code cleanup

- build/testdata/069.build.golden
- build/testdata/069.bzl.golden
- build/testdata/069.in
- tables/tables.go
> Deny sorting for cc_embed_data.srcs

- buildifier/README.md
Update buildifier README.md to use go install @latest command.
Fixes #1019
> Update buildifier README.md to use go install

- edit/buildozer.go
> Fix panic when buildozer is called with an empty command list

- warn/warn_docstring.go
- warn/warn_docstring_test.go
> Fix docstring-related linter errors for nested functions

- warn/warn_control_flow.go
- warn/warn_control_flow_test.go
- warn/warn_naming.go
> Fix 'unitialized' warnings for nested functions and comprehensions

- build/rule.go
and allow RulesAt to find targets nested in list comprehensions, matching the behaviour added to Rules() in
82b21607e00913b16fe1c51bec80232d9d6de31c.
> Consolidate File.Rules() and RulesAt()

- edit/fix.go
The regression was introduced by  #1100
> Fix implicit package declaration handling

- wspace/workspace.go
make `workspace.Find` traverse files in a deterministic way by sorting the files lexicographically.
> Fix flaky config tests

- buildifier/config/config.go
- buildifier/config/validation.go
The methods are used by other packages internally
> Make validation methods exported

- warn/warn_bazel_api.go
- warn/warn_bazel_api_test.go
Also add missing setup calls for other tests.
> Fix load placement for files with docstring and copyright header
