bazelbuild/buildtools

README.md
There is a missing ` at the end of the buildifier command that is
breaking the layout when GitHub renders the README.md file.
Instead, just use the syntax $() to fix this problem.
=> fix rendering of MarkDown file

.gitignore, core/parse.y, core/print_test.go, core/testdata/043.golden, core/testdata/043.in, core/testdata/044.golden, core/testdata/044.in
Also:
* Add .gitignore, as spurious files started appearing in `git status`.
* Fix a panic in the test caused by using `[:len(".txt")]` in the testdata, which creates a zero value for `reflect` on which `Type()` cannot be called.
It'd be nice if long comprehensions would be broken automatically, but being able to force this takes away the immediate pain.
=> Allow forcing multiline for dict and tuple comprehensions

CONTRIBUTORS, WORKSPACE
Fetching via git is slow, buggy, and wastes disk space. It caused a problem for a TensorFlow user in tensorflow/tensorflow#4999. Using http_archive is the optimal solution. I've slowly but surely been updating all the Bazel projects to follow this practice. I've also taken the liberty of mirroring this file for additional reliability.
=> Reference rules_go using reliable http_archive()

WORKSPACE, core/build_defs.bzl
Removes the dependency on `go tool yacc` which is going away in Go 1.8.
Fixes #23
=> use x/tools/cmd/goyacc

WORKSPACE, api_proto/api.gen.pb.go
This is needed to fix an issue with a new Bazel feature, see https://github.com/bazelbuild/bazel/issues/2226 for context.
=> Update rules go to release 0.3.2

WORKSPACE
This updates the go rules past https://github.com/bazelbuild/rules_go/commit/5097c5b883bacb18673145188f6b35fcacdc5d22, which allows the go rules to work
with bazel versions before and after the fix for https://github.com/bazelbuild/bazel/issues/1681 goes in.
=> Update go rules version

buildifier/BUILD.bazel, buildifier/buildifier.go, tables/BUILD.bazel, tables/jsonparser.go, tables/jsonparser_test.go, tables/testdata/simple_tables.json
The `-tables` option makes it possible to specify a JSON file whose
properties define arguments that will be passed to the
`tables.OverrideTables()` function such that other projects can define
their own constraints on argument formatting. This is valuable to
Buck or Skylark users that define rules that need to be formatted in a
way that is different from buildifier's defaults.
Test Plan:
* Added a test: `tables/jsonParser_test.go`.
* Verified that `bazel test //...` succeeds.
* Created a JSON config for Buck and verified the output of the
following was what I expected when run from the Buck repo:
```
export BUILDIFIER_DIFF="diff -u"
find . -name BUCK | xargs -I {} ../buildifier/bazel-bin/buildifier/buildifier -buildifier_disable=label -tables=buildifier.json -d {}
```
For this test, the …
=> Introduce a -tables option.

differ/BUILD.bazel, differ/diff.go, differ/isatty_darwin.go, differ/isatty_linux.go, differ/isatty_windows.go
Without this commit, a build on Windows fails with:
```
differ\diff.go:124 undefined: syscall.Stat_t
```
I had initially tried to use two files and avoid having one file per OS:
1. `isatty_other.go` with `// +build !windows`
2. `isatty_windows.go`
But [build constraints](https://golang.org/pkg/go/build/#hdr-Build_Constraints) require that they be preceded only by line comments or blank lines, they cannot be preceded by the [general comments](https://golang.org/ref/spec#Comments) (`/* ... */`) which are used in the files in this repository.
=> Make buildifier and buildozer compile on Windows

WORKSPACE
This improves reliability and performance because GitHub goes down frequently.
=> Use redundant download URLs

WORKSPACE
For now, downstream users have the following warning message:
```
(@com_github_bazelbuild_buildifier) does not match the name given in the repository's definition (@com_github_bazelbuild_buildtools); this will cause a build error in future versions.
```
=> Update WORKSPACE to reflect the new repo name

edit/edit.go, edit/edit_test.go, unused_deps/unused_deps.go
@pmbethe09, I modified a bit LabelsEqual in order to deal with `.jar-2.params` files notation.
Assuming, that I have a `maven_jar` defined in a WORKSPACE like:
```
maven_jar(
name = "org_apache_commons_commons_lang3",
artifact = "org.apache.commons:commons-lang3:3.1",
sha1 = "905075e6c80f206bbe6cf1e809d2caa69f420c76",
)
```
for every direct dep on it in BUILD file I got in params file following string: `@@org_apache_commons_commons_lang3//jar:jar`
I have two problems with this
1) leading `@@`, that I think should be trimmed (and that's the reason of modifying LabelEquals)
2) `:jar` suffix, that is usually omit in BUILD files. Here, I am not sure about what to do and lean to force administratively demand writing full label name with :jar extension.
WDYT?
=> modify LabelsEqual for unused_deps and some tests

edit/buildozer.go
If a list attribute has a single glob argument, it will now be treated as a literal argument instead.
For example,
`> buildozer 'set srcs glob(["*.go"])' $target`
produces `srcs = glob(["*.go"])` instead of `srcs = ["glob([\"*.go\"])"]`.
To fix https://github.com/bazelbuild/buildtools/issues/99.
=> Handle glob arguments in buildozer.

build/rewrite.go, tables/jsonparser.go, tables/jsonparser_test.go, tables/tables.go, tables/testdata/simple_tables.json
Currently, the priority used to sort named arguments is hard-coded in `build/rewrite`.  This moves and exposes it via `tables.json` to make it customizable.
=> Allowing overriding named argument priority via `tables.json`

build/rewrite.go, buildifier/buildifier.go, tables/jsonparser.go, tables/tables.go
Add `-add_tables` option to buildifier which will merge the user provided tables into the built-in tables, rather than replacing them wholesale. Add ability to override `NamePriority` per rule.
Fixes #112.
=> Support table merging

edit/buildozer.go
Fixes #91.
Regarding CLA, this contribution is being made on behalf of my employer, Facebook.
=> buildozer: make ellipsis work with BUILD.bazel and BUCK files

edit/buildozer.go
gofmt has also removed some whitespace - let me know if that's not desired and I can revert it.
=> Remove references to `g4 edit`

edit/edit.go, edit/edit_test.go
Before: "label" was interpreted as "label:label", but it actually refers
to ":label".
https://docs.bazel.build/versions/master/build-ref.html#labels
=> ParseLabel(): handle labels without colons

buildifier/buildifier.go
Fixes: #110.
The point of check mode is to be able to verify the formatting of BUILD
files from the CI:
```
$ buildifier -mode=check $(find . -name BUILD)
```
Choose the next free return value 4, and return it in case, reformat is
needed.
=> Return non zero code, if check mode failed

WORKSPACE
Required for compatibility with Bazel 0.6+
=> Updated bazel and rules_go versions

wspace/BUILD.bazel, wspace/workspace.go, wspace/workspace_test.go
This can then be used by buildozer to locate such BUILD files. It won't
work for repos defined with Skylark - for example, for [Tensorflow][1]
it could locate models.BUILD but not the BUILD files in third_party.
[1]: https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE
=> Parse WORKSPACE for BUILD files of external repos

edit/buildozer.go, edit/edit.go, edit/edit_test.go
This adds an extra output variable to `ParseLabel()` for the repository,
to support labels of the form `@repo//pkg:rule`. Users of `ParseLabel()`
that don't want to support external repos need to change to:
`_, pkg, rule = ParseLabel(label)`
=> Load BUILD files for external (new_*) repos

WORKSPACE, build/rewrite.go, buildifier/buildifier.go, edit/edit.go, tables/jsonparser.go, tables/jsonparser_test.go
I haven't been able to test this as I get the following error with bazel 0.5.3:
```
ERROR: error loading package 'bazel-buildtools/external/bazel_tools/tools/jdk': Extension file not found. Unable to load package for '//tools/jdk:alias_rules.bzl': BUILD file not found on package path
```
Any idea why that is?
=> Lint and warning fixes

WORKSPACE
also removed the sha26 which is breaking from GitHub.
Fixes https://github.com/bazelbuild/buildtools/issues/139
=> update the WORKSPACE to point to rules_go 0.5.5 

build/lex.go, build/parse.y, build/parse.y.go, build/print.go, build/rewrite.go, build/syntax.go, build/testdata/048.golden, build/testdata/048.in, build/walk.go
This allows {}, {"foo"}, {"foo",}, and such to appear as attribute
values. These are canonically formatted identically to lists.
=> Allow set literals in BUILD files

README.md
The current config on ci.bazel.io rolls all configs into a single (pipeline) job. Which, AIUI, means there's only one badge. This change replaces the three non-working badges with one working one.
=> Fix the ci.bazel.io status badge

edit/buildozer.go, edit/edit.go, edit/edit_test.go
It would be nice to have implicit name recognition to support the smooth integration of buildozer into Pants at Twitter. This allows for target granularity by making targets easier to create. With a [1:1:1 rule](https://www.pantsbuild.org/build_files.html#target-granularity), for one target per directory, the target can implicitly use the directory name.
This code change supports this behavior:
```
When trying to find target //foo/bar/baz:baz
if foo/bar/baz/BUILD does not contain any target with attribute name="baz":
if foo/bar/baz/BUILD contains exactly one target with no name attribute:
treat that target as //foo/bar/baz:baz
```
Original proposal: https://github.com/bazelbuild/buildtools/issues/148
**To verify**
Setup a `tmp` directory with a BUILD file that has only one nameless …
=> Add Implicit Name Recognition

BUILD.bazel, WORKSPACE, differ/BUILD.bazel, differ/diff.go
- Uses `FC` to diff on Windows by default.
- Adds `config_setting` to use `isatty_windows.go` on Windows
- Removes `go_repository` rule that fails on Windows
Fixes: #137
Test: Built and ran `buildifier <file>` and `buildifier -d <file>` on both Windows and Linux
=> Fix differ and make buildifier build on Windows.

build/syntax.go, edit/edit.go, edit/edit_test.go
This is useful for WORKSPACE files in particular, eg:
`buildozer 'print name' WORKSPACE:%http_archive`
Make sure that ParseLabel doesn't interfere with absolute paths to
support this overloading.
=> Allow buildozer to edit arbitrary files

wspace/workspace.go, wspace/workspace_test.go
=> Accept either WORKSPACE or .buckconfig as indicating repo root.

WORKSPACE
With latest Bazel at HEAD, this results in an error, as rules_go already
imports the repository. If it is needed at a different version than
rules_go uses, the go_repository definition needs to be before the call
to go_repositories().
Also update the reference to io_bazel to the latest released version.
=> Remove duplicate declaration of org_golang_x_tools.

build/print_test.go, build/rewrite.go, build/testdata/049.golden, build/testdata/049.in, build/testdata/049.stripslashes.golden, tables/jsonparser.go, tables/jsonparser_test.go, tables/tables.go, tables/testdata/simple_tables.json
Pants has this behaviour. This is completely configurable through tables.json, so shouldn't affect anyone who doesn't want this behaviour.
Also, treat //foo:bar to be equivalent to :bar in foo/BUILD
The three commits should be usefully independently reviewable.
=> Allow tables.json to configure label default behaviour to strip leading //

edit/buildozer.go
This was breaking some workflow: when using the print command, you
expect this is the only thing on stdout (with the change, the whole file
was printed as well).
=> Rollback change related to --stdout

edit/edit.go
This modifies the behavior of Buildozer and breaks existing users. Once
the depot is in a more stable state, we can try to reintroduce this
feature (maybe with a special syntax?).
=> Disable the UseImplicitName feature.

buildozer/main.go
This adds an equivalent flag from buildifier to buildozer to load the tables from a custom JSON-encoded path.
=> buildozer: add `-tables` flag to load tables.json from file

wspace/workspace.go, wspace/workspace_test.go
Before, this would break with:
File not found: /path/to/workspace/third_party:repo.BUILD
=> Fix paths for build files inside packages

build/rewrite.go, build/testdata/050.golden, build/testdata/050.in, build/testdata/050.stripslashes.golden
Unless the current BUILD file is in the root directory.
=> Don't strip // prefix for targets in the root BUILD file

WORKSPACE
I also took the liberty of making sure these URLs were mirrored.
=> Use sha256 and https for Bazel mirror URLs

buildozer/main.go
Given #113 and #167, it seems obvious that we should have -add_tables for Buildozer too.
=> Introduce -add_tables for Buildozer

edit/BUILD.bazel, edit/types.go, tables/jsonparser.go, tables/tables.go
The default implementation of `edit.types.IsList` consults `lang.tables.TypeOf`. This means that the definition of whether a given label represents a list argument is essentially hardcoded into buildifier and buildozer.
Some consumers may wish to customize this value for certain labels. Introduce a feature that allows you to override the default value using the tables feature.
=> Allow overriding IsList via -tables

buildozer/README.md
It was already listed in the examples below but not in the list of commands.
=> Mention attribute removal in documentation.

build/lex.go, build/parse.y, build/parse.y.go, build/print.go, build/syntax.go, build/testdata/051.formatbzl.golden, build/testdata/051.golden, build/testdata/051.in, edit/edit_test.go
End statement tracking wasn't accurate and didn't always work well, but on the other hand it was used only for implicit `;` insertion (which is not required for Skylark syntax, removing an explicit `;` from the end of a line never changes Skylark semantics).
However proper end statement tracking is crucial for bzl files parsing: files are not just sequences of top-level statements, it's important to see where each node ends.
Statements are now considered ended before `\n` of their last line, and the `\n` is now passed to the parser explicitly.
=> Fix end statement tracking

BUILD.bazel, build/BUILD.bazel, build/build_defs.bzl, build/checkfile_test.go
See the discussion in https://github.com/kubernetes/test-infra/pull/4859
This enables dep/Gazelle to strip this test when vendoring.
=> Change the genfile_check_test to a go_test.

buildozer/main.go, edit/buildozer.go
Motivation: make it safer to run multiple edit.Buildozer() commands simultanously.
=> Replace global edit.Opts with a local variable

build/lex.go, build/parse.y, build/parse.y.go, build/testdata/052.golden, build/testdata/052.in
All augmented assignments except `//=` are supported here. `//=` will be supported in a follow-up commit because `//` is currenlty not supported too.
Fixes #200
=> Support augmented assignments

buildozer/README.md, edit/buildozer.go, edit/edit.go, edit/edit_test.go
Substitute lets users perform substitution in string values using
regular expressions. This is a more powerful command than replace; it
should be useful for updating deps after moving a large number of
libraries.
Fixes #182
=> edit: add new substitute command for buildozer

build/lex.go, build/syntax.go
It turns out this information is duplicated (Comments already knows
what is suffix) and not used outside the lexer. It was also confusing:
someone modifying the AST might rely on it, when it's actually ignored
by the pretty-printer.
=> Remove the `Suffix bool` in the Comment structure.

build/lex.go, build/parse.y, build/parse.y.go
After this change, 'load' cannot be used as an identifier.
AST isn't changed though (it still uses a CallExpr). Updating the AST
will require changing users of the library.
=> Treat 'load' as a syntax keyword

build/rule.go, build/rule_test.go, build/syntax.go, edit/buildozer.go, edit/edit.go, edit/edit_test.go
This means that 'print' commands understand implicit names, and that
implicit names are understood by default in all commands, rather than
needing to be handled as special cases everywhere.
=> All of buildozer is aware of implicit names

build/lex.go, build/parse.y, build/parse.y.go, build/parse_test.go, build/print.go, build/rewrite.go, build/rule.go, build/rule_test.go, build/syntax.go, edit/buildozer.go, edit/edit.go, edit/fix.go
Add more information to the AST, which will help tools build on top of
it. The definition of Ident matches the one from
https://github.com/google/skylark/blob/master/syntax/syntax.go
This is a breaking change, some users might need to be updated.
=> Introduce "Ident" node, to distinguish between numbers and idents.

build/syntax.go
The nodes are not yet used, so that we can update users in a
non-breaking way.
=> Add new nodes "Ident" and "LoadStmt"

build/lex.go, build/parse.y, build/parse.y.go, build/print.go, build/syntax.go, build/testdata/016.golden, build/testdata/016.in, build/testdata/053.formatbzl.golden, build/testdata/053.golden, build/testdata/053.in
Make the parser compliant with the Skylark spec (https://docs.bazel.build/versions/master/skylark/spec.html)
This change adds additional syntax primitives (such as Test, Argument, Parameter), which makes the parser stricter (disallows some invalid expressions that were previously allowed, e.g. `[a = b]`, `f(*****d)`), but on the other hand allows implicit tuples that were previosly not supported: `a, b = c, d`.
Fixes #199.
=> Refactor the parser

buildozer/README.md
I'm not a Go expert, but at least on my pretty standard Linux and macOS systems, that's all that is needed.
FWIW, the instructions for `buildifier` already look like this, too.
=> Simplify installation instructions for buildozer.

buildifier/buildifier.go
In the future the default behavior for buildifier will be to format files as if they are bzl files (at least when they're passed through stdin, when the file names are not known).
For now the default behavior will remain the same (format files as they are BUILD files) for compatibility reasons, but users will be able to provide `--type=build` explicitly to avoid breaking in the future.
=> Change a flag for switching between build and bzl modes

build/parse.y, build/parse.y.go, build/testdata/051.build.golden, build/testdata/051.bzl.golden, build/testdata/051.in
This commit fixes a bug because of which the following syntax was considered invalid:
if True: pass
else: pass
=> Allow compact if-elif-else statements to be separated by empty lines

build/print.go, build/testdata/051.build.golden, build/testdata/051.bzl.golden, build/testdata/051.in
Format def statements in a multiline mode differently:
* Use 8 spaces instead of 4 for indentation
* If the last argument doesn't have a comment, the closing bracket is printed on the same line
* The comma after the last argument is never printed (it's not valid to print it after *args or **kwargs)
=> Format def statements

build/lex.go, build/parse.y, build/parse.y.go, build/print.go, build/syntax.go, buildifier2/convert_ast.go
Implicit tuples (e.g. `a, b = c`) used to be detected based on the fact that the line number of opening brackets for such tuples is 0 which can't be true if a bracket has been parsed from a real file. However, a tuple generated by a refactoring tool always has zeroed positions, meaning that their line numbers for all elements including the brackets are all 0. This commit resolves the ambiguity by using an explicit boolean flag for bracketless tuples.
=> Don't format non-tuple sequences as implicit tuples

build/parse.y, build/parse.y.go, build/testdata/054.build.golden, build/testdata/054.bzl.golden, build/testdata/054.in
If-else chains that don't end with an else block (e.g. a single `if` or `if-elif`) used to be a syntax error.
=> Fix if-else statements

build/lex.go, build/parse.y, build/parse.y.go, build/print.go, build/testdata/052.golden, build/testdata/052.in
Pipes are not defined in the spec, but still exist in .bzl files as legacy depset operators, therefore they should be supported by a formatting tool.
=> Support pipes as binary operators

unused_deps/unused_deps.go
Bazel's `-2.params` files will escape any argument starting with `@` by prepending them with `@`. This could be to escape `@file` parameter expansion but I haven't looked into it deeply enough to confirm that.
=> Handle @file escapes.

unused_deps/unused_deps.go
According to the best practices [a project should always be able to build `//...`](https://docs.bazel.build/versions/master/best-practices.html#running-builds-and-tests), so it seems like a good default to use for `unused_deps`.
=> Default to `//...` if no target patterns are specified.

build/rule.go, build/rule_test.go
"If a build file contains exactly one unnamed rule" currently matches the load statement in the following:
```
load("//foo", "some_rule")
some_rule(
name = "bar",
)
```
This is clearly not the intent of the implicit rule name case, so tweak it accordingly.
=> load statements are not eligible for "implicit rule names"

unused_deps/unused_deps.go
When building a `java_library` with resources Bazel will build a class jar separately from the final jar.
This means the params file is going to have a different prefix compared to the jdeps file. If the `java_library` has no resources this is not the case, so we have to try to read both paths.
=> Handle `java_library` with resources.

build/print.go
Non-top-level statements (i.e. statements inside def, for, if or else blocks) should be formatted in the bzl mode even if buildifier is run in the build mode. Rationale: such blocks are not allowed in BUILD files in Bazel anyway, but if that's allowed anywhere else, contents of such blocks are usually not declarations of targets but some auxiliary commands.
The tests are not affected by this change because the build mode still uses legacy PythonBlock nodes that are printed as is. Once it's removed, the tests will be fixed accordingly.
=> Format non-top-level statements in the default mode

edit/edit.go
This allows `@com_google_guava_guava//jar:jar` to be shortened to `@com_google_guava_guava//jar` for example.
This affects both `buildifier` and `unused_deps`: `unused_deps` isn't able to detect unused deps specified with the short hand right now.
Is "cross repo" the right nomenclature?
=> Shorten cross repo labels.

build/rule.go
Now that literals and identifiers are represented as different AST nodes, the AttrLiteral method should take that into account and check for both possibilities.
=> Fix the AttrLiteral method

edit/edit.go
Loads should be added after the  """docstring comment""" at the top of the file.
=> Update InsertLoad to respect docstring comments.

buildifier/buildifier.go, differ/diff.go
"error strings should not be capitalized or end with punctuation or a newline"
=> Fix a linter error

build/lex.go, build/parse_test.go, build/print.go, build/print_test.go, build/syntax.go, buildifier/buildifier.go, edit/buildozer.go, edit/edit_test.go, tables/tables.go
Currently buildifier chooses the formatting mode by looking at the global variable `tables.FormattingMode`. This approach has disadvantages: it's hard to use buildifier as a library (not clear at which step the variable should be set), it makes it impossible to format files of different types in parallel.
The proposed approach is to save the information about the file to the File object during the parsing step. In the end there should be a `Parse` method that does it automatically by looking at the file name, and two explicit methods `ParseBuild` and `ParseDefault` for selecting the build or default mode for a given file.
Currently the `Parse` method is already used for BUILD files, so it's temporarily kept as an alias for `ParseBuild`. The next step will be to make all the existing users …
=> Introduce new parse methods

build/print.go, build/testdata/057.golden, build/testdata/057.in
The trailing comma currently causes Skylark to fail to load formatted files.
=> Omit trailing comma in calls with *args and **kwargs parameters

build/lex.go
In some cases the lexer adds comments with an empty string as a token to the tree to separate comment blocks inside a statement (e.g. if a list contains line comments inside). Such fake comments don't have real `Start.Byte` values, instead the value is the same as for the next real comment line.
Later, when the comments are sorted to restore the possibly broken order, such comments order can be broken by unstable sorting algorithms.
=> Use sort.SliceStable instead of sort.Slice

build/print.go, build/testdata/051.build.golden, build/testdata/051.bzl.golden, build/testdata/051.in
`return  a + b` used to be formatted as `return (a + b)` by mistake.
=> Fix precedence for returned expressions

build/print_test.go
Two more tests to ensure that the build mode is stricter than the bzl mode:
1. `.build.golden` files aren't changed after being formatted in the bzl mode. (bzl(build(file)) == build(file))
2. `.bzl.golden` files become equal to the corresponding `.build.golden` after formatting in the build mode. (build(bzl(file)) == build(file))
Idempotence for equal modes has already been covered by other tests.
=> Add quasi-idempotence tests

build/lex.go, build/print_test.go, build/rewrite.go, build/testdata/055.golden, build/testdata/055.in, buildifier/buildifier.go
Load arguments should be sorted by the Rewrite method. Items with equal "from" and "to" parts (`foo="foo"` or just `"foo"`) should be prioritized over keyword arguments with different values (`foo="bar"`) so that the syntax remains valid Python syntax.
=> Sort load args

build/print.go, build/testdata/051.build.golden, build/testdata/051.bzl.golden, build/testdata/051.in
=> Use original printing style for arguments of a function definition

build/print.go, build/testdata/002.build.golden, build/testdata/002.bzl.golden, build/testdata/060.golden, build/testdata/060.in
=> Keep single quotes for string literals instead of escaping double quotes inside

build/parse.y, build/parse.y.go, build/print.go, build/testdata/051.build.golden, build/testdata/051.bzl.golden, build/testdata/058.golden, build/testdata/058.in
In Skylark comments are allowed to be indented freely, not necessarily following the current indentation level. If an indented block ends with a comment, like the following:
def f():
pass
f()
it's not clear if the comment belongs to the block or to the outer level. This PR disallows indented blocks to end with a comment, so they will be treated either as standalone outer level comments or comments attached the next statement, depending on the existence of an empty line between the comment and the next statement. In theory it's possible to allow the following:
def f():
pass
f()
but for the simplicity and consistency it's better to always move trailing comments from an indented block to the level above. Otherwise the following may occur: if a user adds a line (`f()`) to the example below: …
=> Indented comments

build/testdata/059.golden, build/testdata/059.in
The text in the test is confusing because doesn't reflect the actual behaviour.
=> Fix a test

build/parse.y, build/parse.y.go, build/testdata/044.build.golden, build/testdata/044.bzl.golden, build/testdata/044.in
Comprehensions should be formatted in the multiline mode not only if there's a line break after the opening bracket, but also if there's a line break before each of the for- and if- clauses and before the closing bracket. This behavior is consistent with how sequences (lists, dicts, tuples, arguments lists) are printed in buildifier.
Fixes #301.
=> Fix multiline comprehensions

build/lex.go
1. A hashmap is used instead of a list.
2. The variable is now exported so that it can be adjusted from a binary that calls `build.Parse`.
=> Improve type detection

build/rewrite.go
Fixes "don't use underscores in Go names".
=> Fix a golint warning

build/print.go, build/testdata/044.build.golden, build/testdata/044.bzl.golden, build/testdata/044.in
Comments for `ForClause` and `IfClause` were disappearing because these nodes weren't printed by `p.expr` that's capable of handling the comments.
=> Fix line comments inside comprehensions

build/rewrite.go, build/testdata/059.golden, build/testdata/059.in
If a docstring's `Value` is changed when it's being re-indented, also change its `Token` similarly to preserve user's choice of escaping unicode symbols. The printer checks if a `Value` is equal to an unquoted `Token`, and if that's true, doesn't quote `Value` and reuses `Token`.
=> Fix extra escaping in indented docstrings

buildifier/BUILD.bazel, status.sh
This enables use of newer versions of rules_go that only support
x_defs.
Note: the STABLE_ prefix on status script variables is required to
force a re-link when values change.
Fixes #322
=> buildifier: migrate linkstamp to x_defs in go_binary rule

build/rewrite.go, build/testdata/059.golden, build/testdata/059.in
When a docstring is indented by buildifier, its contents is also indented. However if a line in a docstring ends with `\`, its value doesn't get a linebreak there, but this linebreak should be taken into account when the docstring is being indented, because it exists in the source file.
The indentation of a docstring should be performed over its `Token` attribute instead, and the `Value` attribute should be re-unquoted from `Token`.
=> Fix docstrings indentation

build/parse.y, build/parse.y.go, build/testdata/051.in, build/testdata/058.golden, build/testdata/058.in
The current version of buildifier moves all trailing comments of an indented block to the outer block. However sometimes users expect trailing comments to belong to the indented block:
if foo:
pass
This example was previously formatted as the following (which can be considered as a bug):
if foo:
pass
However `pyformat` understands that this is not a top-level comment and doesn't dedent it.
This pull request makes the trailing comment detection smarter: if checks for the indentation level of each trailing comment line and only dedents the first comment line with indentation level less than the block indentation level, and all following comment lines.
=> Implement smarter trailing comments detection

build/parse.y, build/parse.y.go, build/testdata/052.golden, build/testdata/052.in
`a | b | c` was erroneously formatted as `a | (b | c)` because the tree was parsed right-to-left.
Partially fixes #280.
=> Fix the pipe operator precedence

config/config.go, unused_deps/unused_deps.go
Newer versions of Bazel write "-2.params" files with a different format.
This patch handles the change.
=> Add support for "-2.params" files that contain --direct_dependencies.

build/print.go, build/testdata/061.golden, build/testdata/061.in
A long chain of dot expression can be intentionally printed in a multiline mode to avoid long lines. Buildifier doesn't try to avoid long lines on its own, therefore it should respect multiline formatting if it's enforced by the author.
=> Allow dot expressions to be multiline

build/rewrite.go, build/testdata/062.build.golden, build/testdata/062.bzl.golden, build/testdata/062.in
If a list is marked with a "keep sorted" comment explicitly it should be sorted in the bzl mode (as well as in the build mode).
=> Sort lists in the bzl mode

buildifier/runner.bash.template, status.sh, update_generated.sh
This helps with nixos where bash is installed elsewhere by default. (after fixing the cla of course...)
=> More portable bash invocation

buildozer/BUILD.bazel, buildozer/main.go
shortenLabelsFlas is being used in edit ShortenLabels function
but not used in rewrite ShortenLabels, which causes all the labels to be
shorten though this flag is set to false.
=> Disable label rewrite if shortenLabelsFlag is false

edit/buildozer.go
Certain transformation that shouldn't be applied to a certain rule (e.g. add new rule) should be called exactly once for a file.
Fixes #362.
=> Fix global transformations with filters

build/syntax.go
Span() is support to return a semi-inclusive interval, although for some nodes it return the position of the last byte instead of the next byte.
=> Fix spans for various nodes

buildozer/README.md, edit/buildozer.go
My personal use case is something like:
```
load("@tagged_docker_push//:defaults.bzl", tagged_docker_push = "docker_push")
```
=> Support new_load /foo to=from

edit/edit.go
It's useful to search for used symbols not only in the file, but inside certain nodes with its own scope (like DefStmt).
=> Refactor UsedSymbols

build/rewrite.go
This upstreams an internal change which corrects the Buildifier's
rewrite behavior when the call site is a DotExpr as opposed to an Ident.
=> Correctly interpret call context with DotExprs.

buildifier/def.bzl
Today if the buildifier rule user runs `bazel test //...` on their project, buildifier-wrapping bash script will be built along with buildifier itself and everything it depends upon (go sdk, etc).
This change wraps the rule invocation in a macro to add the "manual" tag to it so that it is not matched by wildcard target patterns.
This is the same technic that is used in gazelle https://github.com/bazelbuild/bazel-gazelle/blob/82d15888a19178195d56d9a288a2653d16436b07/def.bzl#L116
=> Add manual tag to the constructed buildifier target

buildifier/README.md, update_generated.sh
When passing this to the current version of bazel (0.17.2) bazel warns
since this flag is deprecated now.
=> Remove deprecated --direct_run flag

build/rewrite.go
To fix https://github.com/bazelbuild/buildtools/issues/381
This reverts commit 89e7689ad55d09641266a829a71a74c9f757009f.
=> Revert "Correctly interpret call context with DotExprs. (#378)"

WARNINGS.md
Github-flavored markup only supports html anchors
=> Fix the anchors

WARNINGS.md, warn/warn.go, warn/warn_test.go
Although `unused-load` is more informative, there are already existing tools that expect that the category is called `load` and they were broken because of the name has been changed. This commit reverses the change.
=> Rename unused-load to load

buildifier/deps.bzl
I was trying to update dependency on this repository in one of my projects and encountered an error:
```console
bazel run //:buildifier
INFO: Build options have changed, discarding analysis cache.
ERROR: /private/var/tmp/_bazel_ash2k/f36748a9f0eb432c2fc5416fedbad4c7/external/com_github_bazelbuild_buildtools/build_proto/BUILD.bazel:10:1: no such package '@io_bazel//src/main/protobuf': The repository could not be resolved and referenced by '@com_github_bazelbuild_buildtools//build_proto:copy_and_fix'
ERROR: Analysis of target '//:buildifier' failed; build aborted: Analysis failed
```
This repo also has a target `//:buildifier`. Here are dependency paths for the version I use and for current master:
Hash 47728e38feb98d5f354ea1eb99e0e44f0e4d7a14
```console
bazel query 'somepath(//:buildifier, …
```
=> Add missing dependency on io_bazel to buildifier rule

buildifier/integration_test.sh, warn/warn.go
* `--lint=fix` now sorts warnings by line number for every file
* `--lint=warn` doesn't show unfixed warnings (but shows their count)
=> Update console output for linter messages

.gitignore
The directory is automatically created by the [Intellij with Bazel](https://plugins.jetbrains.com/plugin/8609-bazel) plugin.
=> Add .ijwb to .gitignore

warn/warn_bazel.go, warn/warn_bazel_test.go
Not only have some of the context actions been renamed, their signature has also been changed. This change allows automatic fixes to update the signature.
=> Fix automatic fixes for deprecated actions

warn/types.go, warn/types_test.go
The `%` operator can be applied to expressions of different types. If the left side is a string, the right side
can be anything and the binary expression itself will be a string.
Therefore we can't assume that the result of `unknown % type_x` is of type X, unless it is a string, e.g. compare `10 % 3` and `"template %s" % 3`.
Likewise, the `%=` operator can also be applied to a string and a non-string.
=> Fix the type inference with the % operator

WARNINGS.md
For each linter category:
* specify its name explicitly (it can be used in the command line with the `--warnings` flag
* provide a link to the corresponding incompatible flag in Bazel if available
* specify whether it has an automatic fix
=> Document warning categories

build/BUILD.bazel, build/lex.go, build/lex_test.go
When using Bazel external workspaces, it's common to have files named like something.BUILD or BUILD.something, which become the BUILD file for the `@something` repository. This CL modifies build.ParseDefault so that it considers any filename with an extension or base called "BUILD" to be a BUILD file. While workspace file naming in the wild is less creative, I didn't see a reason not to extend the same rule to workspace files.
The build.BuildFilenames variable is public, so I preserved its behavior as an override. If it's not actually considered a public API, I can delete it.
=> Expand the set of file names considered to be build files.

buildozer/README.md, edit/buildozer.go, edit/edit.go
(This supercedes #376 to deal with CLA; all credit to @PaulSonOfLars)
This address issue #126, adding dictionary manipulation tools.
Specifically, this adds the following to buildozer:
`dict_add <attr> <(key:value)(s)>` Which does not overwrite existing values.
`dict_set <attr> <(key:value)(s)>` Which overwrites existing values.
`dict_remove <attr> <key(s)>` Which removes keys from the dictionary, removing the final dictionary if it is now empty.
=> Add dictionary handling

WARNINGS.md, warn/warn.go, warn/warn_test.go
Loads like
```
load(":f.bzl", "s1")
load(":f.bzl", "s2")
```
can be simplified as
```
load(":f.bzl", "s1", "s2")
```
which is more concise and less error prone.
=> [buildifier] Warn and fix loads from the same file.

WARNINGS.md, warn/warn.go, warn/warn_bazel_test.go, warn/warn_test.go
* `native.anything` shouldn't be used in BUILD files
* `native.package()` shouldn't be used in .bzl files.
The last check is the first to affect only .bzl files, that's why the tests needed to be refactored to be able to specify custom scope (i.e. BUILD files, .bzl files or any files), a boolean flag `isBuildFileSpecific` wasn't enough anymore. In the future that can also be expaned to WORKSPACE files.
=> Add a warning and fixes for wrong usages of `native.`

warn/warn.go, warn/warn_test.go
When the same symbol is loaded multiple times, during evalution the
last symbol wins and all previous loads are ignored, but `buildifier`
would preserve the first instance and remove all other usages
which breaks semantics unless all loads are from the same file.
In other words
```
load(":defs1.bzl", "s1")
load(":defs2.bzl", "s1")
```
is equivalent to
```
load(":defs2.bzl", "s1")
```
but `buildifier` would produce
```
load(":defs1.bzl", "s1")
```
To address this, all statements are analyzed in a reverse order, so the very
last (in terms of line numbers) is preserved and all preceding loads are
removed. This also slightly simplifies `load` removal logic, since we no longer
need to adjust index.
=> [buildifier] Preserve symbol semantics when removing unused loads.

WARNINGS.md, warn/warn.go, warn/warn_test.go
This makes it easier to developers to locate loads, but more
importantly reduces changes for large-scale automated refactorings
to result in merge conflicts, since they usually add loads at the
end or some other fixed position.
=> [buildifier] Warn about and fix non-lexicographic load order.

buildifier/def.bzl
If you use buildifier within bazel this allows you to set the
`lint_mode` on your rule.
=> Support buildifier lint within bazel

build/lex.go, build/lex_test.go, build/parse_test.go, build/print.go, build/rewrite.go, build/syntax.go, buildifier/buildifier.go, convertast/convert_ast.go, edit/edit.go, warn/warn.go, warn/warn_test.go
Currently, a boolean flag is used to distinguish between .bzl and BUILD files, and WORKSPACE have been treated like BUILD files. However there are differences, certain refactoring tools (such as moving all load statements on the top) shouldn't be apllied to WORKSPACE files, but can be applied to BUILD files.
This PR creates a new type FileType to represent multiple file types (currently there are three types available).
Also the `--type` flag now accepts a new value (`workspace`).
=> Support WORKSPACE files

WARNINGS.md, warn/warn.go, warn/warn_test.go
With the support of WORKSPACE files it's now possible to include or exclude them from the scope of various lint warnings.
This CL excludes WORKSPACE from the `out-of-order-load` and `load-on-top` warnings, as load statements may appear anywhere in any order in WORKSPACE files.
Fixes #449
=> Fix scopes for warnings

buildifier/buildifier.go, buildifier/integration_test.sh, warn/warn.go, warn/warn_test.go
Previously every file that was processed by the buildifier -lint=fix
command would produce output, even if there weren't any fixes. To make
this more like the buildifier fix formatting mode, this wraps that print
in the `-v` flag.
=> Only print lint fixes with verbose mode

buildifier/README.md, buildifier/deps.bzl
5816db19ef74 updated WORKSPACE, but did not update buildifier's deps.bzl
and README.md files.
=> Align version of bazel and rules_go in buildifier/ as well

buildifier/buildifier.go
The `lint` flag controls the mode used for linting and is super useful.
Fixes #443
=> [buildifier] Add lint flag to usage.

warn/warn.go, warn/warn_test.go
`register_toolchains` accepts a sequence of strings instead of
keyword arguments.
Fixes #454
=> [buildifier] Do not warn about positional args used for register_toolchains.

warn/warn.go, warn/warn_test.go
Currently the warning would be printed in case two identical labels
are compared, which cannot be fixed, since reordering the same load
would not change the comparison result.
This change makes the warning flag only instances where `i`th label
is "less than" the `i-1`th label.
=> [buildifier] Fix load order comparison warning.

WARNINGS.md, warn/BUILD.bazel, warn/warn.go, warn/warn_test.go
Since it's common to use dictionaries for passing `**kwargs` to rules, their
ordering should match the ordering used rule attributes in build files.
Build files rely on `NamePriority` `tables` dictionary to adjust priorities
according to common or project-specific guidelines and now the same rules
apply to ordering dictionary items.
=> [buildifier] Take name priority into account when ordering dictionary items.

warn/warn.go, warn/warn_test.go
Symbols that start with `_` are private and should follow public
symbols to make user experience better.
=> [buildifier] Sort private symbols after public.

buildifier/buildifier.go, warn/warn.go
PrintWarnings functions handles the logic of warning presentation and
as such should not be responsible for anything else. It was also
accepting unnecessarily many arguments, making it harder to use.
The comment was also not explaining what a returning value meant.
=> [buildifier] Refactor warn.PrintWarnings function.

differ/diff.go
/bin/bash does not exist on every distribution, /usr/bin/env does and
it autodetects the executable, so this is best practice.
=> differ: use /usr/bin/env bash

buildifier/buildifier.go
This extends usage information with all existing flags and their
defaults:
```
...
Buildifier's reformatting depends in part on the path to the file relative
to the workspace directory. Normally buildifier deduces that path from the
file names given, but the path can be given explicitly with the -path
argument. This is especially useful when reformatting standard input,
or in scripts that reformat a temporary copy of a file.
Full list of flags with their defaults:
-add_tables string
path to JSON file with custom table definitions which will be merged with the built-in tables
-allowsort string
additional sort contexts to treat as safe
-buildifier_disable string
list of buildifier rewrites to disable
-d	alias for -mode=diff
-lint string
lint mode: off, warn, or fix (default off)
-mode …
```
=> [buildifier] Include all flags in usage info.

WORKSPACE, buildifier/deps.bzl
Seeing as these are already imported via buildifier_dependencies they are redundant.
In response to a [comment](https://github.com/bazelbuild/buildtools/pull/478#issuecomment-446767227) on an earlier PR, and I figured this would make updating versions easier. 
There is a bit of a nasty catch however, in our setup we noticed that the loading of the dependencies isn't entirely deterministic when using the _maybe rules (different target run calls may load different versions of the same dependency).
So if you intended it this way, feel free to disregard the PR.
=> Remove skylib and io_bazel dependencies from WORKSPACE

buildifier/buildifier.go
Previously, only the lines were output, which makes tracking down the
changes a bit hard.
I’m assuming the `--mode=diff` output is not intended to be parse-able by e.g. `patch`, but I might be wrong.
=> Display the filenames for --mode=diff

warn/warn.go, warn/warn_test.go
Check for load statements being not on the top is essential for .bzl files because it's going to be an error in Bazel to do so.
However despite it's also consistent to have load statements on top for BUILD files as well, that doesn't work well with existing BUILD files generators that often put load statements right before they are needed.
=> Disable load-on-top warnings for BUILD files

build/lex.go, build/syntax.go, buildifier/buildifier.go, warn/warn.go
Currently if the file is read from stdin its filename is stored as "stdin", which is used not only for printing but also for some internal logic (e.g. when `--mode=diff` is used and the file comes from stdin it should be saved to a temporary file for comparison).
It's more clear and less error-prone if such files have no filename (`""`) and the word "stdin" is used only for representation.
=> Don't use the name 'stdin' for standard input

buildifier/buildifier.go, buildifier/integration_test.sh, warn/warn.go
* Mark certain warnings as non-default (currently `out-of-order-load` and `unsorted-dict-items`), they won't be applied unless explicitly added (or with `--warnings=all`)
* Allow users to provide `+` and `-` modifiers to the warnings list. E.g `--warnings=-foo,+bar` means all default warnings except "foo" but with "bar" (which is assumed to be non-default).
Fixes #493
=> Provide a flexible way of enabling disabling warnings

warn/warn.go, warn/warn_test.go
Previously, the sorting was performed based on the entire module string
lexicographically, which would result in somewhat suboptimal ordering of
things like
```
load("//foo2:mno.bzl", "mno")
load("//foo:xyz.bzl", "xyz")
```
and
```
load("//foo/bar:mno.bzl", "mno")
load("//foo:xyz.bzl", "xyz")
```
This change makes it so the ordering logic first tries to compare loads
by package alone and break ties using file names.
Fixes #501
=> [warn] Sort loads by package and file name separately.

buildifier/def.bzl
This mode was added a year ago but was never added as an option to the
buildifier rule which makes it inaccessible to those that use buildifier
through the rule
=> Add `print_if_changed` as a mode in the buildifier rule

build/print.go, warn/warn.go, warn/warn_test.go
When the `same_origin_load` fix merges two load statements it currently creates a multi-line load statement in any case (because the loaded symbols were originally located on different lines).
With the update they will be merged into a single-line load statement if both original load statements were also single-line.
=> Merge two single-line load statements into a single-line one

build/lex.go, warn/warn.go, warn/warn_test.go
If a symbol is loaded twice from the same label, it's safe to delete the second time it's loaded. It may be not safe to delete the first time because it may be used in between.
If a symbol is loaded twice from different labels, it's not safe to automatically delete it, instead just a warning should be shown. For instance, the following code should be fixed manually by renaming the loaded symbols and eliminating the confusion:
load("foo", "a")
a()  # from foo
load("bar", "a")
a()  # from bar
=> Safer duplicated load fix

WARNINGS.md, warn/warn.go, warn/warn_test.go
Warn about statements that are not reachable by the execution.
=> Warnings for unreachable statements

WARNINGS.md, warn/warn.go, warn/warn_bazel.go, warn/warn_bazel_test.go
If a function is used as a rule implementation, it's recommended that it doesn't return old style structs.
=> Warn about old-style function implementation function returns

buildifier/buildifier.go, buildifier/def.bzl, buildifier/runner.bash.template
The current technique buildifier uses to select a diff program and set the multidiff flag is
obscure.  It relies on undocumented environment variables, involves grepping for the
string "tkdiff" in a command name, etc.  Buildifier should take command line arguments
instead.  As a first step toward this goal, let's add flags for the diff program and whether
it supports tkdiff-style multi diff.  Later, we can deprecate the undocumented environment
variables, etc.
=> Add command line arguments -diff and -multi_diff.

build/print_test.go, build/rewrite.go
* `filepath.Dir` and `os.PathSeparator` (or `filepath.Separator`) should be used instead of `path.Dir` and `'/'` while working with actual filenames.
* When paths are converted to labels, `filepath.Separator` should be replaced with `'/'` explicitly.
This commit should fix tests that are currently failing at #522.
=> Fix Windows-specific incompatibilities

build/lex.go, build/parse.y, build/parse.y.go, build/print.go, build/syntax.go, convertast/convert_ast.go, warn/warn_control_flow.go
Currently the `Ident` node is used to represent `pass`, `break`, and `continue` statements, which made the following code valid:
if break:
pass + continue
=> Create a separate node for pass, break, and continue statements

buildifier/buildifier.go
When argument parsing fails, output a usage message to standard error.  When
run with "-help", output a usage message to standard output.
=> Add "-help" command line argument.

WARNINGS.md, build/walk.go, warn/warn.go, warn/warn_naming.go, warn/warn_naming_test.go
All variables should be lower_snake_case, constant should be UPPER_SNAKE_CASE, and providers should be UpperCamelCase ending with `Info`.
=> Warnings for variable names

build/rule.go
Sync with the internal repository
* Add the `NewRule` helper function.
* Fix the usage of `implicitName` (it shouldn't be applied for `package()` calls).
=> Sync rule.go

warn/warn_control_flow.go, warn/warn_control_flow_test.go, warn/warn_docstring_test.go
For-loop variables are not guaranteed to be initialized after the loop, but are initialized inside it.
=> Fix uninitialized variables warnings

warn/warn_docstring.go, warn/warn_docstring_test.go
If a function is private or not long enough, don't force its docstring to have arguments or the return value documented.
However if at least some arguments are documented, check that all of them are.
=> Update the functions docstring warning

warn/warn_docstring.go, warn/warn_docstring_test.go
It's common that a function has many arguments and a docstring that doesn't document them.
In this case instead of generating multiple warnings (one for missing documentation) buildifier should generate one cumulative warning to reduce the warning noise.
=> Compress multiple 'not documented' warnings into one warning

build/rule.go, warn/warn_bazel.go, warn/warn_bazel_test.go, warn/warn_test.go
Implicit names shouldn't be taken into account when checking for duplicated rule names.
Fixes #553
=> Fix duplicated names warning with implicit names

warn/warn_docstring.go, warn/warn_docstring_test.go
The `Arguments:` section often may contain empty lines or have no empty line between itself and the next section (e.g. `Returns`), buildifier shouldn't warn that these sections don't exist.
Fixes #551
=> Make the function docstring check more flexible

warn/warn_bazel_api.go, warn/warn_bazel_api_test.go
If a positional argument is a binary expression but not with `=` as an operator, `MakePositional` should leave it as it is.
=> Fix ctx-actions automatic fix

buildifier/def.bzl
When running with bazel this allows you to pass arguments to enable /
disable lint rules
=> Add support for lint command line args with bazel

edit/buildozer.go
When a multiline comment is added with buildozer's "comment" function, it was added as a single comment node with linebreaks, instead it should be added as multiple one-line comment nodes for buildifier to be able to format the AST correctly.
Fixes #556
=> Fix multiline comments

warn/warn_cosmetic.go, warn/warn_cosmetic_test.go
If a symbol is loaded from not a label (a string that doesn't contain a `:`), the `out-of-order-load` check may crash with index error.
May be related to #541
=> Fix out-of-order-load checks

build/lex.go, build/lex_test.go, build/print.go, build/print_test.go, build/rewrite.go, buildifier/buildifier.go, warn/warn.go, warn/warn_bazel.go, warn/warn_bazel_api.go, warn/warn_bazel_api_test.go, warn/warn_bazel_test.go, warn/warn_control_flow.go, warn/warn_cosmetic.go, warn/warn_cosmetic_test.go, warn/warn_docstring.go, warn/warn_docstring_test.go, warn/warn_test.go
Previously buildifier distinguished BUILD, WORKSPACE, and all other files (the latter were .bzl files). However buildifier can be applied to other types of Starlark files (e.g. copybara configuration files), and its bzl-specific lints shouldn't be applied to them.
This commit introduces TypeBzl reserved for Bazel's .bzl files, and fixes some checks (mostly the checks for Bazel build API usages) to not be applied to generic Starlark files.
=> Introduce separate Bzl and Default filetypes

build/lex.go, build/parse.y, build/parse.y.go, build/parse_test.go, build/print.go, build/rewrite.go, build/rule.go, build/rule_test.go, build/syntax.go, build/walk.go, build/walk_test.go, bzlenv/bzlenv.go, convertast/convert_ast.go, edit/buildozer.go, edit/edit.go, edit/edit_test.go, edit/fix.go, warn/types.go, warn/warn_bazel.go, warn/warn_bazel_api.go, warn/warn_bazel_operation.go, warn/warn_control_flow.go, warn/warn_cosmetic.go, warn/warn_docstring.go, warn/warn_naming.go, warn/warn_operation.go
Assignment expressions are special cases of binary expressions with operator == "=", they are often treated specially in various lint checks: as statements they define new (local) variables, as expressions inside other statements they correspond to keyword parameters.
=> Introduce an AssignmentExpr node

build/lex.go, buildifier/integration_test.sh
In the case the user doesn't pass a specific inputType for files passed
with stdin we now change the inputType to default
Fixes https://github.com/bazelbuild/buildtools/issues/568
=> Set inputType to default for stdin

build/print.go, build/testdata/054.golden, build/testdata/054.in
Don't compress "else-if" to "elif" if the "if" statement has a comment before.
Fixes #570
=> Fix lost comments in if-else chains

warn/warn.go, warn/warn_cosmetic.go, warn/warn_cosmetic_test.go
If buildifier applies `out-of-order-load` without applying `load-on-top` (either because of the flags or because "load-on-top" is not enabled for BUILD files), it may occur that there are other statements between load statements that depend on the first load, and swapping the loads lead to a breaking change:
load(":b.bzl", "b")
b()
load(":a.bzl", "a")
With this update buildifier only sorts consequent chunks of load statements (i.e. load statements without other statements between them). Comments between the load statements are fine as long as they belong to one of the load statements, the following will be sorted:
load(":b.bzl", "b")
load(":a.bzl", "a")
The following will not be sorted:
load(":b.bzl", "b")
load(":a.bzl", "a")
Fixed #575
=> Fix out-of-order-load warnings

edit/buildozer.go, edit/buildozer_command_file_test.go
If a buildozer command file contains a really long command (e.g. a
command adding many source files to a target), buildozer gets confused
and parses that line incorrectly. This happens because
bufio.Scanner.Text fails if a line exceeds the buffer size (64 KiB [1]).
Avoid the buffer size limit by using bufio.Reader.ReadString instead of
bufio.Scanner. This allows buildozer to handle commands larger than 64
KiB.
[1] https://github.com/golang/go/blob/456f3e10cdee774ccf12121f47b88865a3777e7c/src/bufio/scan.go#L79
=> Remove limits on buildozer command file line lengths

edit/buildozer.go
Underscores shouldn't be used in Go variable names.
=> Rename a variable

buildifier/BUILD.bazel, buildifier/README.md, buildifier/buildifier.go, buildifier/integration_test.sh, buildifier/utils.go
If an argument to buildifier is not a file but a directory, recursively find all relevant Starlark files in it (i.e. with extensions `.bzl`, `.sky`, `.build`, or `.workspace`, or with names `build.*` or `workspace.*`, case insensitively).
Fixes #516.
=> Find relevant Starlark files recursively in directories

buildifier/BUILD.bazel, buildifier/buildifier.go, buildifier_utils/BUILD.bazel, buildifier_utils/utils.go
A separate package that can be used from different implementations of `buildifier.go` for shared logic.
=> Create a buildifier_utils package

buildifier/BUILD.bazel, buildifier/buildifier.go, buildifier/utils/BUILD.bazel, buildifier/utils/utils.go
This improves readability (a package-specific utils are now in a subpackage) as well as Go lint errors ("don't use an underscore in package name").
=> Move buildifier_utils to buildifier/utils

warn/warn_control_flow.go, warn/warn_control_flow_test.go, warn/warn_cosmetic.go, warn/warn_cosmetic_test.go
Make warning messages for some categories more readable:
For already loaded symbols mention line numbers where the load occurs.
For not used loaded symbols provide a workaround for reexporting symbols.
=> Update warning messages

buildifier/buildifier.go, buildifier/integration_test.sh, buildifier/utils/BUILD.bazel, buildifier/utils/flags.go
Currently it's not allowed to combine `--lint=warn` with any value of `--mode` except `--mode=fix` (which is default). It makes it not possible to print lint warnings without reformatting a file.
`--lint=fix` still requires `--mode=fix` because applying fixes involves reformatting.
Fixes #453
=> Allow --lint=warn to be combined with any value of --mode

warn/warn_bazel.go, warn/warn_bazel_test.go
These two functions still don't exist in BUILD files as builtin functions, the warning and the fix are currently not correct.
Related Bazel issue: https://github.com/bazelbuild/bazel/issues/7496
=> Temporarily exclude `native.existing_rule` and `native.existing_rules` from the warning

build/lex.go, build/print.go, build/quote.go, build/quote_test.go, build/rewrite.go, edit/buildozer.go, edit/fix.go
If buildozer expects a value to be a string, it quotes it unconditionally. If the string provided is already quoted it will be doublequoted:
$ buildozer set cmd "foo" :target
will result in
cmd = "\"foo\""
The commit fixes the behavior by attempting to unquote the string, and, if can be unuqoted, using the unquoted value instead of the original value.
=> Allow providing quoted strings for string values

edit/edit.go
#609 makes it possible to provide both quoted and unquoted strings for string values. However the `remove` and `dict_remove` commands still don't support quoted values, which makes opposite commands (like `add` and `remove`, or `dict_add`(`set`) and `dict_remove`) not exactly opposite: `add args "foo"` adds a string `'foo'` and `remove args "foo"` attempts to remove `'"foo"`.
=> Make remove and dict_remove commands compatible with add commands

buildifier/buildifier.go, buildifier/utils/BUILD.bazel, buildifier/utils/tempfile.go, buildifier/utils/utils.go
Remove the global variable `toRemove` by replacing it with a class that keeps track of created temp files and cleans them up in the end.
=> Refactor WriteTemp

buildifier/integration_test.sh, buildifier/utils/utils.go
Skip directories named as Starlark files (e.g. `build/` or `workspace/`).
Skip .git directories entirely.
Fixes #614
Fixes #624
=> Fix -r flag

buildifier/buildifier.go, buildifier/integration_test.sh, buildifier/utils/diagnostics.go
Stdin filename is represented as `""` internally but should be printed as `<stdin>`.
=> Print correct filenames in case of stdin input

status.py
`status.sh` is used by BazelCI to build buildtools-related binaries, but it can't be used on Windows.
`status.py` is a multiplatform alternative, it will completely replace `status.sh` once the latter is not used anymore by the CI configuration.
#375
=> Rewrite status.sh in Python

status.py
Python 3 prints byte strings as their `repr`:
>>> print(b'asd')
b'asd'
They need to be converted to unicode before printing.
=> Fix status.py for Python 3

build/parse.y, build/parse.y.go, build/syntax.go, warn/warn_docstring.go, warn/warn_docstring_test.go
In case there is no module or function docstring, buildifier attaches a warning to the first non-comment statement in the sequence (of file or function statements). This may look fine in the console (because the console only shows line numbers of the findings beginnings, however looks weird in CIs where a warnings is usually shown right after its range ends. Thus, if a module has no docstring and starts with a long function definition, the warning is shown after the last line of the function. If a function has no docstring and starts with a long if- or for-block, the warning will be shown somewhere in the middle of the function.
This PR fix the issue: "no module docstring" will always be attached to the range of the first symbol of the first non-comment statement of the file, "no function …
=> Fix docstring warnings ranges

warn/warn_bazel_api_test.go
Warning messages use values that can be overridden using tables.go, the test should also take it into account, otherwise it will fail when the warning message is overridden.
=> Fix TestNativeAndroidWarning

warn/warn_bazel.go, warn/warn_bazel_test.go
Now that `existing_rule` and `existing_rules` are available in BUILD files, buildifier can remove the `native.` prefix for them as well.
https://github.com/bazelbuild/bazel/issues/7496
=> Remove the special case for existing_rule(s)

edit/edit.go, warn/warn.go, warn/warn_control_flow.go
#655 and #656 slightly changed the behavior of some functions (i.e. differently formatted warnings, different Load statements were modified if multiple loads from the same file were found, etc). This PR restores the previous behavior.
=> Restore the old behavior

warn/warn.go, warn/warn_bazel.go
Cleaning up the unused chunks of the code, also making it possible to have rule warning and file warning functions with different signatures (file warning functions don't need the `pkg string` parameter, rule warning functions return at most one warning per rule).
The PR is required for the compatibility with some internal-only warnings.
=> Cleanup the code after the refactorings

build/syntax.go, warn/warn.go, warn/warn_test.go
The current mechanism of disabled warnings is out of date, it was designed to work with BUILD files and doesn't take nested statements into account. Because of that it wasn't possible to disable a warning for a statement inside a function, if- or for-block.
Besides, the special comment syntax required mentioning "buildozer", although warnings are primarily generated by buildifier now. Now it's possible to use "buildifier" instead:
foo()  # buildifier: disable=warning1
bar()  # buildozer: disable=warning2
Fixes #661
=> Fix disabling warnings

buildifier/integration_test.sh, buildifier/utils/utils.go, buildifier/utils/utils_test.go
Buildifier recognizes files called `build`, `workspace.oss` (lowercase), or `foo.BZL` as BUILD, WORKSPACE, and .bzl files respectively if the filenames are provided explicitly, however in the `-r` mode it shouldn't parse such files, normally Starlark files shouldn't be called like that, and buildifier is likely to crash with a syntax error if it attempts to parse files that it's not supposed to.
Fixes #662
=> Make recursive file detection stricter

build/rule_test.go
Remove dangling %s format arg that would not cause compilation issues in default mode.
t.Errorf("TestImplicitName(%s): got %s, want %s.", tst.description, got, tst.want)
=> Fix BUG: Remove bad format string arg

buildozer/README.md, edit/BUILD.bazel, edit/buildozer.go, edit/buildozer_test.go
This command removes the comment attached to the specified rule, attribute, or value in an attribute.
=> Add `remove_comment` command to Buildozer.

warn/warn_docstring.go
A recent change has broken the position of "no function docstring" warnings. Their span should be just the function's header (from `def` till `:`), not the whole body.
=> Fix function docstring warning position

buildifier/README.md
The previous instructions don't work with new versions of bazel like
0.28.0.
=> Update buildifier setup instructions.

WARNINGS.md, tables/tables.go, warn/warn.go, warn/warn_bazel_api.go, warn/warn_bazel_api_test.go
This change adds a fix for the native-to-starlark migration of Protobuf
rules. Also, the implementation is refactored to add support for warnings
when symbols should be loaded.
/cc @hlopko @lberki @iirina
=> Add native-proto fix to buildifier

warn/warn_cosmetic.go, warn/warn_cosmetic_test.go
package-on-top shouldn't be triggered if there are nil statements (e.g.
added by another warning function to be able to provide fixes).
=> Fix the package-on-top warning

WORKSPACE, build/parse.y, build/parse.y.go, build/print.go, build/syntax.go, build/testdata/053.build.golden, build/testdata/053.bzl.golden, build/testdata/053.in, buildifier2/buildifier2.go, convertast/convert_ast.go
Keyword-only parameters are now permitted in Starlark (https://github.com/bazelbuild/starlark/issues/23), and are supported by the parser in starlark-go. This PR adds the new syntax to `parse.y` for `buildifier`, and upgrades the starlark-go dependency for `buildifier2`.
=> buildifier: Support keyword-only parameters

buildifier/buildifier.go, buildifier/integration_test.sh
The `--path` argument should affect everything except the actual reading of the input file, including linter warning messages.
Fixes #475
=> Fix the usage of the --path argument

warn/warn_bazel_api.go
Warnings "Function is not global anymore" are currently bound to entire CallExpr nodes, if buildifier is used in IDEs, entire target definitions become underlined, which produces a lot of noise. With this change the behavior is chahged to only match `CallExpr.X` nodes, which for global functions is just their name (or maybe `native.<function_name>` in .bzl files).
This doesn't affect the console output because it only mentions start lines, which is the same for a call expression node and its `.X` subnode.
=> Change the span for not loaded function warnings

buildifier/def.bzl
This adds support for `--incompatible_restrict_string_escapes` https://github.com/bazelbuild/bazel/issues/8380
=> Update bzl escape for incompatible flags

build/build_defs.bzl
I can't find any evidence that this genrule must run locally. It works when run remotely in Stripe's hermetic remote build environment, which is stricter than e.g. RBE, so I figure it's probably safe to remove the "force local build" argument.
Fixes #601
=> Allow go_yacc genrule to be executed remotely.

buildifier/buildifier.go, buildifier/integration_test.sh
The flag should only affect the file names in the output, it shouldn't affect the actual path the file is read from and written to.
=> Fix the behavior of the --path flag

WARNINGS.md, warn/warn.go, warn/warn_bazel_api.go, warn/warn_bazel_api_test.go
Replaces legacy keyword arguments with positional arguments in some builtin functions, e.g. `bool(x = foo)` -> `bool(foo)`.
bazelbuild/bazel#5010
=> Fix for legacy named arguments

WARNINGS.md, warn/warn.go, warn/warn_operation.go, warn/warn_operation_test.go
=> Add a warning for invalid string sequences

warn/warn_operation.go
If multiple warning functions are applied to the same AST, another may generate a StringExpr node with an empty Token field. Such nodes can't have wrong escape sequences because their value will be encoded to a string literal later correctly, and they can cause index out of bound errors if buildifier attempts to parse their Token fields.
=> Fix the string escape warning

warn/warn_docstring.go, warn/warn_docstring_test.go
If the `Returns:` section contains a line starting with `foo:` (for example, a link starting with `https://`), buildifier parses it as an argument description (and usually shows a false-positive warning for an argument which is documented but doesn't exist).
=> Fix false positive argument detection for function-docstring-args

WARNINGS.md
* Replace links to backward-compatibility.html (now 404) with links to the Github issues.
* Add a single section describing how to disable warnings.
=> Cleanup WARNINGS.md

WARNINGS.md, buildifier/integration_test.sh, warn/warn_docstring.go
Users often confuse docstrings with comments, make the difference clear.
=> Disambiguate the definition of docstrings

warn/warn_control_flow.go, warn/warn_control_flow_test.go, warn/warn_operation.go
If a no-effect warning is triggered by string expressions, additional explanation about docstrings is shown.
=> Update the warning about unused statements

buildifier/def.bzl
In a repo with custom Bazel rules, we need to tell buildifier to sort additional list than those defined by default. This diff allows use to pass in a JSON file like:
```
{
"IsSortableListArg": {
"topics": true
}
}
```
So the buildifier will sort `topics` list in BUILD files too.
=> expose add_table flag to buildifier rule

warn/warn_bazel_api.go
Rename it to NotLoadedFunctionUsageCheck so that it can be used from other packages.
=> Export notLoadedFunctionUsageCheck

BUILD.bazel, WARNINGS.md, build/syntax.go, buildifier/buildifier.go, buildifier/utils/utils.go, warn/BUILD.bazel, warn/warn.go, warn/warn_test.go, warn/warn_visibility.go, warn/warn_visibility_test.go
If a .bzl file is located within a directory called `private` or `internal`, it should only be loaded from files located directly or indirectly in the directory parent to `private` or `internal`.
Fixes #702.
=> Implement .bzl files visibility warning

edit/edit.go
`ResolveAttr` simplifies a rule attribute by concatenating the lists and extracting common elements from selects, however it can be applied to attributes that has just been deleted, in that case it should do nothing (as opposed to setting the attribute's value to `nil` which leads to a broken AST).
=> Fix ResolveAttr

buildifier/runner.bash.template
Add `(BUILD|WORKSPACE).*.(oss|bazel)` pattern in `runner.bash.template` so that they are processed on `bazel run //:buildifier`. Those patterns are introduced in f8b2ce4c.
Fixes #704
=> buildifier: Add additional patterns in runner.bash.template

warn/warn_operation.go, warn/warn_operation_test.go
The `string-escape` check shouldn't be applied to raw string literals.
=> Allow string escapes for raw strings

buildozer/README.md, edit/buildozer.go, edit/buildozer_test.go
We've recently added a build attribute which is a [string_list_dict](https://docs.bazel.build/versions/master/skylark/lib/attr.html#string_list_dict), just to find out that there is no way to operate on such an attribute from buildozer, so I'm sending this PR. Thanks.
Example:
```
buildozer 'dict_list_add attr key1 value1 value2' 'dict_list_add attr key2 value3' //some/target
```
Should generate:
```
a_rule(
name = "target",
attr = {
"key1": [
"value1",
"value2",
],
"key2": ["value3"],
},
)
```
Internal bug: b/22484279
=> buildozer: Add command for appending to lists in a dict attribute

edit/buildozer.go, edit/buildozer_test.go, edit/edit.go
The behavior was partially broken by #732. `targetExpressionToBuildFiles` was returning incorrect results if it was called with an empty `rootDir` parameter and a `target` containing `"..."` (e.g. when buildozer was called with `...:*` as a target).
=> Fix targetExpressionToBuildFiles

build/print.go, build/testdata/055.golden, build/testdata/055.in, warn/warn_cosmetic_test.go
If a statement has an after-comment it should be seaparated from the next statement by an empty line:
foo()
bar()
The problem can't occur during formatting because the formatter attaches comments to the statement after by default, but it can occur if the parsed AST has been modified, e.g. during the `load-on-top` fix.
=> Print an empty line after statements with after-comments

edit/buildozer.go
This is a repeat of #730.  I opened the original with the wrong account for the CLA.
If a dictionary value contains a :, then the value is not parsed correctly. Need to preserve everything after the first :. One example where this comes up is setting environment variables for paths when using container_image from the docker rules. For example, when running dict_add env PATH:/a/b/c:/d/e/f it ends up only including /a/b/c and it ignores /d/e/f.
=> Fix parser for adding to dictionary

build/rewrite.go
The function existed purely for legacy reasons, it wasn't used in the opensource buildifier anyway, now it's not being used internally as well.
=> Remove legacy DisableLoadSortForBuildFiles

WARNINGS.md
This is basically GitHub SEO.
I'm adding this out of frustration I had while trying to find how does one suppress Buildifier warnings. I was sure I saw it somewhere in the docs but couldn't find it because I was searching for "suppress" and "ignore" but not the "disable" 😅
=> Add "disable" keywords for better docs search

edit/buildozer_test.go
Fixes https://github.com/bazelbuild/buildtools/issues/763
=> fix order dependency by adding a defer to Chdir back to the original

warn/warn_docstring.go, warn/warn_docstring_test.go
It's possible that the arguments are documented but not correctly and Buildifier fails to parse that. If Buildifier thinks that no arguments are documented at all, print some additional information on how exactly the documentation should look like.
=> Improve the warning message if no documented args are found

build/quote.go, build/testdata/060.golden, build/testdata/060.in
All backslashes now should be unconditionally escaped in string literals.
The behavior was broken by #762  
Fixed #766
=> Fix string quoting

tables/tables.go, warn/warn_cosmetic.go, warn/warn_cosmetic_test.go
Rule attributes are sorted lexicographically but with a few exceptions, e.g. "name" should be the first item, "srcs" should be placed before "deps", etc.
The same list of exceptions (https://github.com/bazelbuild/buildtools/blob/master/tables/tables.go#L108) was used for sorting dict keys, however that's often confusing: if a dict's items don't represent rule attributes, it's not clear why, for example, the following ordering is correct: `{"name": ..., "first_name"; ..., "last_name": ...}`
The pull request removes the exceptions for dict keys, except for "//conditions:default" which is often used in dicts in select statements and should be the last by convention.
Fixes #760
=> Don't use tables.NamePriority for sorting dict items

WORKSPACE, api_proto/BUILD.bazel, build_proto/BUILD.bazel, deps_proto/BUILD.bazel, extra_actions_base_proto/BUILD.bazel
Make the repository compatible with the following Bazel flags:
* --incompatible_load_cc_rules_from_bzl
* --incompatible_load_proto_rules_from_bzl
* --incompatible_use_platforms_repo_for_constraints
Fixes #755 
Fixes #756 
Fixes #757
=> Make buildtools compatible with future releases of Bazel

warn/warn_docstring.go, warn/warn_docstring_test.go
If a function signature contains arguments with asterisks ("*args" or "**kwargs") users often forget to include the asterisks into the documentation, which causes warnings like `Arguments "*args", "**kwargs" are not documented` and `Argument "args" is documented but doesn't exist in the function signature`. To avoid the confusion, the latter warning message is extended with `Do you mean "*args"?` (or `"**kwargs"`) if such an argument actually exists in the function signature.
Closes #768
=> Improve the warning message for missing argument documentation

edit/buildozer.go, edit/edit_test.go
=> Allow buildozer arguments to be joined with newlines

WORKSPACE, buildifier/BUILD.bazel, buildifier/utils/BUILD.bazel, buildozer/BUILD.bazel, bzlenv/BUILD.bazel, warn/BUILD.bazel
The old repository definition is broken on the CI for Windows (but somehow works on the other platforms). Updating it fixes the problem (and also updates the dependency to the latest version).
Fixes #776
=> Update the skylark_syntax repo

edit/buildozer.go
#773 allows buildozer arguments to be separated by linebreaks. However in some cases it's required to have linebreaks inside arguments (e.g. for adding multiline comments), in such cases it should be allowed to use escaped linebreaks, such as:
$ buildozer 'comment srcs a.cc Just\ a\
multiline\ comment' //my:package
=> Allow escaped linebreaks in buildozer command arguments

buildifier/BUILD.bazel, buildozer/BUILD.bazel, unused_deps/BUILD.bazel
Add new build targets for `buildifier`, `buildozer`, and `unused_deps` for building all binaries for all platforms.
Simply running `bazel build //buildifier:buildifier-windows` will build a correct binary for Windows regardless of the current platform. It will make it possible to automatically release buildtools by just running a single script.
=> Add multiplatform build targets

.bazelrc, BUILD.bazel, WORKSPACE, buildifier/BUILD.bazel, buildifier/package.json, buildozer/BUILD.bazel, buildozer/package.json, launcher.js, release.sh, status.py
This replaces the mirroring we currently do in https://github.com/bazelbuild/rules_nodejs/blob/master/scripts/mirror_buildtools.sh
=> Add publishing to npm

build/syntax.go, buildifier/buildifier.go, buildifier/integration_test.sh, buildifier/utils/BUILD.bazel, buildifier/utils/utils.go, buildifier/utils/utils_test.go, warn/warn.go, warn/warn_test.go, warn/warn_visibility.go
The warning didn't work correctly with relative file paths.
=> Fix .bzl visibility warnings

buildifier/integration_test.sh, warn/warn.go
Now that the warning has been fixed and tested better, it can be enabled by default.
=> Enable bzl-visibilty warnings by default

build/quote.go, build/testdata/060.golden, build/testdata/060.in
Strings like `"\120\113"` won't be reformatted as `"PK"`.
=> Allow any characters in string literals to be escaped as code points

WORKSPACE, buildifier/deps.bzl
Commit `98244f725d46ab37614ac6bbb653a6827a46fabd` introduced an implicit
dependency on `rules_nodejs` within `//buildifier:BUILD`, which breaks
downstream user's ability to run Buildifier.
This patch uses the `_maybe()` rule (defined within
`//buildifier:deps.bzl`) to conditionally register
`@build_bazel_rules_nodejs` so that downstream users do not need to
define this internal dependency within their `WORKSPACE`.
closes bazelbuild/buildifier#796
=> fix(buildifier): add rules_nodejs to //buildifier:deps.bzl target

warn/warn_visibility.go, warn/warn_visibility_test.go
If a private .bzl file which is allowed to be loaded from the current file is loaded using a fully quailfied path (including a repository name), buildifier shows a false positive warning for the `bzl-visibility` category.
This change makes buildifier ignore the repository name, which may mute some true positive warnings (if a file is being loaded from another repository but with a similar directory structure) but it also mutes the false positives.
Fixes #718.
=> Mute false positive warnings for private .bzl files

WARNINGS.md, buildifier/integration_test.sh, buildifier/utils/utils.go, warn/BUILD.bazel, warn/multifile.go, warn/warn.go, warn/warn_deprecated.go, warn/warn_deprecated_test.go, warn/warn_docstring.go, warn/warn_test.go
Deprecated funcitons are defined in other .bzl files, so buildifier is now also able to read from loaded .bzl files.
=> Implement deprecated function warning

WARNINGS.md
=> Remove string-escape from warnings, this option is no longer supported.

build/print.go, build/print_test.go, build/rewrite.go, build/syntax.go, buildifier/buildifier.go, buildifier/integration_test.sh, buildifier/utils/diagnostics.go, edit/buildozer.go, edit/edit.go, warn/types_test.go, warn/warn_docstring_test.go, warn/warn_test.go
Currently to format a file one should call two separate functions:
* `build.Rewrite(file, &rewriteInfo)`: to modify the AST in-place (e.g. to sort the load arguments or to replace the division operator `/` with the integer division operator `//`). This function also takes an output argument of the type `*build.RewriteInfo` which is actually not useful (the diagnostics are being printed to the console but users are usually interested in whether the file has been reformatted or not, rather than how many division operators were fixed).
* `build.Format(f)`: to actually convert the AST to bytes.
This is confusing for users who use buildifier as a library. If they don't know that they need to call `Rewrite` they may end up with incorrectly sorted load arguments if they add new loads.
The PR …
=> Refactor rewrites

build/syntax.go, buildifier/buildifier.go, buildifier/integration_test.sh, buildifier/utils/utils.go, buildifier/utils/utils_test.go, warn/multifile.go, warn/warn_deprecated.go, warn/warn_deprecated_test.go, warn/warn_macro.go, warn/warn_macro_test.go, warn/warn_test.go, warn/warn_visibility.go, warn/warn_visibility_test.go
Currently buildifier determines a file's package as its base name (relative to the workspace root). Although that's always true for BUILD files, .bzl files may be located not necessarily in a package root but in a subdirectory.
That didn't matter before, but now with the functionality of loading additional .bzl files that's being used by some analyzers, it's important to know the current file's package to resolve relative labels correctly.
To achieve that it's enough to locate a BUILD file closest to the initial file; all other loaded files packages can be determined by analyzing their label: e.g. if "//some/package:label/name.bzl" is loaded, the package is set to "some/package" and the label to "label/name.bzl" without even looking at BUILD files.
=> Fix file packages

buildifier/utils/diagnostics.go, buildifier/utils/utils.go
* #815 by mistake removed the `# reformat` line from the output, restored.
* The logic for splitting a relative path into package and label (by looking for a BUILD file) has been moved to a separate function because it can be reused in situations when a workspace root is already known.
=> Fixes for resolving import errors

release/github.sh, release/npm.sh
Add a script that can automatically create a draft release with an empty description. Generated draft releases contain everything else: correct tag, name and uploaded binaries for all platforms.
=> Authomatise GitHub release process

warn/warn_macro.go, warn/warn_macro_test.go
Private functions can't be imported at BUILD files and therefore can't be macros.
=> Don't apply unnamed-macro to private functions

build/rewrite.go, tables/tables.go
The config variable `tables.SortableWhitelist` wasn't handled correctly. The bug wasn't noticeable because the variable wasn't actually used anyway (all its values are already implicitly listed in `tables.IsSortableListArg`).
=> Fix SortableWhitelist

warn/warn_docstring.go, warn/warn_docstring_test.go
=> Correctly parse docstrings in CRLF-formatted files

WARNINGS.md, warn/warn_macro.go, warn/warn_macro_test.go
Make the build warning for lack of `name` in a macro keyword arguments more clear.
=> Clarify unnamed macro warning

edit/buildozer.go, edit/buildozer_test.go, edit/edit.go
I tested this locally, and seemed to work for some commands like `set` and `add`
Even though buildozer had support for custom build file names, it didn't work for all commands like `add`. This was due to the assumption of `BUILD` file name in `edit.go`. This PR should fix that.
=> Thread through build file names to edit.go

build/build_defs.bzl
genrules require a bash shell, making them incompatible with
Windows unless a mingw dependency is added.
I made the private rule 1:1 compatible with the previous macro genrule
implementation in case there are some dependent repositories that use it.
=> Replace genrule in go_yacc with custom bzl rule.

lang/defs.bzl
Otherwise it can't be overridden internally.
=> Make the parameter 'bin' public

build/walk.go
In order to be able to suggest replacements without applying them, buildifier can insert nil nodes that are no-op for the printer but can be replaced with new nodes if required. Such nodes can cause NPE in some other linter functions that can operate on a modified AST with nil nodes if not handled properly.
Some of such NPEs can be avoided if `build.Walk()` and `build.WalkPointers()` don't call the callback function on such nil nodes.
=> Fix nil nodes traversal

edit/buildozer.go, edit/buildozer_test.go
Copybara invokes buildozer by passing the relative path to a
BUILD file using Unix separator.
This was broken in 19db42aa7a by the introduction
of `filepath.FromSlash` when evaluating the path to BUILD files.
Instead we can make it more tolerant by accepting both forms.
=> Fix windows handling of path to build file containing "/"

buildozer/buildozer_test.sh, edit/buildozer.go, edit/edit.go
Buildozer can now work with comments (e.g. print them) for strings inside select statements.
=> Fix working with comments inside select statememnts

build/parse.y, build/parse.y.go, build/syntax.go, build/walk.go, convertast/convert_ast.go, edit/edit.go, warn/warn_cosmetic.go
`DictExpr` objects may contain subnodes of any types that implement `Expr`. This commit restricts it to `KeyValueExpr` objects only, which makes the AST more correct and traversing it easier.
=> Restrict dict elements to KeyValueExpr objects

build/walk.go
Some call sites of `build.Walk` expect `KeyValueExpr` nodes to be visited explicitly.
=> Fix dict nodes traversal

build/parse.y, build/print.go, build/testdata/006.build.golden, build/testdata/006.bzl.golden, build/testdata/006.in
Lambdas and sets are supported by Starlark-in-go and are supported by Buildifier already but haven't been covered by tests.
#852
=> Add tests for lambdas and sets

warn/warn_cosmetic.go, warn/warn_cosmetic_test.go
The `skylark-docstring` and `skylark-comment` check may yield some false positive warnings if the word "skylark" is a part of a link for the official Starlark documentation, such as `https://docs.bazel.build/versions/master/skylark/lib/Label.html`.
The fix suppresses the warning if the word "skylark" is prepended to or followed by a slash, this will cover this URL and potentially some other URLs too.
=> Don't warn about using "skylark" inside URLs

warn/warn_docstring.go
The problem was introduced in #837. The return value of `getDocstring` has been changed from `build.Expr` to `*build.Expr` which made it possible to return `&nil` for special nil-nodes inserted by other linter/fixer functions.
That can lead to NPEs if such values are treated as `Expr` nodes, also that was not correct because nil-nodes should be ignored by linters that haven't created them.
=> Fix potential NPE

warn/warn_cosmetic.go, warn/warn_cosmetic_test.go
If a `skylark-docstring` warning is disabled by a special comment `# buildifier: disable=skylark-comment`, it triggers the `skylark-comment` warning. This commit fixes that.
Fixes #865.
=> Don't warn about disabling comments

warn/warn.go, warn/warn_test.go
A warning can be attached not to an AST node itself but to a comment line. A disabling comment (`# buildifier: disable=...`) should also disable such warnings.
Fixes #867
=> Make disabling comments also disable warnings for comments

edit/fix.go, edit/types.go
The attribute doesn't contain labels, the values shouldn't be shortened.
=> Decree package_group.packages as a non-label attribute

build/parse.y, build/parse.y.go
Shift/reduce conflicts are automatically resolved to "shift", I've made this behavior explicit to get rid of the warning messages.
Fixes #280
=> Get rid of the shift/reduce conflicts in the yacc grammar

LICENSE
While I was doing the [buildozer formula migration](https://github.com/Homebrew/homebrew-core/pull/57242), I found the license in here is causing some issue.
Now looking at [Bazel](https://github.com/bazelbuild/bazel/blob/master/LICENSE) and [Bazelisk](https://github.com/bazelbuild/bazelisk/blob/master/LICENSE) repos, they are both using Apache 2.0. Thus replacing the existing LICENSE with the same version.
cc @philwo
=> license: update lic to apache 2.0

build/rewrite.go, build/testdata/047.build.golden, build/testdata/047.bzl.golden, build/testdata/066.golden, build/testdata/066.in
This transformation applies only in a few safe cases. Parens are
preserved in multiline expressions, in presence of a comment, or in
complex expressions.
This change can modify the formatting of existing files, but such cases
should be relatively rare.
=> Automatically remove superfluous parens

buildifier/README.md, buildifier/utils/flags.go
It's a typo in both error message and the doc, should be `--mode=check` instead of `--type=check` :)
I tried using it with `--type=check` and was getting following error:
```console
buildifier -v --format=json --type=check myfile.bzl
buildifier: unrecognized input type check; valid types are build, bzl, workspace, default, auto
```
=> Fix wrong error msg & doc about --mode=check

buildozer/buildozer_test.sh, edit/buildozer.go
An AST after buildozer transformations may be not correct, e.g. it may have an `Ident` node with a complex expression inside. In order to format such AST correctly it should be printed to a string, re-parsed correctly and printed again.
Fixes #894
=> Format files with a builtin buildifier correctly

edit/edit.go, edit/edit_test.go
Some methods have been moved from `edit` to `labels` in #903. They are still being used internally, so they should be restored for backward compatibility.
=> Restore removed methods

buildozer/buildozer_test.sh, edit/buildozer.go, edit/edit.go
#903 removed support of the `--shorten_labels` flag, however there are still few usages of it, and it should be restored.
At the same time, `ShortenLabel` was also used to compare labels, where 1. the flag shouldn't play any role, 2. it's not necessary because `labels.Equal` can correctly compare long and short labels.
=> Restore the --shorten_label flag

edit/buildozer.go, edit/edit.go, edit/fix.go, labels/labels.go, labels/labels_test.go, warn/warn_deprecated.go, warn/warn_macro.go
E.g. `labels.ParseLabel()` -> `labels.Parse()`.
=> Rename methods to avoid repetition

warn/types.go, warn/types_test.go, warn/warn_control_flow.go, warn/warn_control_flow_test.go
The `redefined-variable` check disallows modifying top-level variables, however the `+=` operator on lists doesn't redefine them but just modifies them in-place, that should be allowed.
=> Allow += on top level lists

unused_deps/unused_deps.go
I've added better support for jdeps in the Bazel Kotlin rules
see: https://github.com/bazelbuild/rules_kotlin/pull/415
Namely we now specify a `--direct_dependencies` flag to the KotlinBuilder to match how Bazel's JavaBuilder works. This is basically the API that unused_deps uses to understand a targets direct dependencies.
This changes the unused_deps tool to also include `kt_*` rules for processing and also needs to check `KotlinCompile` mnemonics since Kotlin targets with no Java sources will not invoke a `Javac` action.
=> Support Kotlin Rules

build/testdata/006.build.golden, build/testdata/006.bzl.golden, build/testdata/006.in, convertast/convert_ast.go
Note that in my own usage of buildifier2 the example I provided gets `build.FormatString`-ed onto just one line:
```starlark
TriggerActionAfterProbe(probe = ("http", "response"), predicate = lambda State, response: all([response["request"]["method"] == "GET", response["request"]["url"].find("/posts/") != -1, response["request"]["url"].endswith("/comments"), response["status_code"] in range(200, 299)]), action = lambda State, response: None)
```
I wonder what's different with this test suite. And now writing all this I'm guessing either
* my code isn't being exercised by the tests, or
* the tests use different formatting settings
I'll look into it (any ideas though?)
Anyway, buildifier2 would crash without this clause.
=> buildifier2: support lambda expressions

buildifier/buildifier.bzl, buildifier/def.bzl, buildifier/internal/factory.bzl, buildifier/runner.bash.template
```
This patch adds a `buildifier_test` rule, as well as a factory-based
workflow for generating both rules to reduce the burden of maintenance.
closes #928
```
---
This looks like a lot, but there are a few things to keep in mind:
* The `buildifier()` implementation has not been changed at all
* The factory-based approach taken here _really_ simplifies the burden of maintenance, as both the executable and test rules share basically, well, everything -- and without the factory-based approach, there'd be a lot of manual duplication.
---
Usage looks like this:
**`//foo:BUILD.bazel`**
```
STARLARK_FILE_GLOB = [
"**/*.BUILD",
"**/*.bzl",
"**/*.sky",
"**/BUILD",
"**/BUILD.*.bazel",
"**/BUILD.*.oss",
"**/BUILD.bazel",
"**/WORKSPACE",
"**/WORKSPACE.*.bazel",
"**/WORKSPACE.*.oss", …
```
=> feat(buildifier): add buildifier_test

buildozer/main.go, edit/buildozer.go
This updates buildozer to accept multiple command files, reading and executing the instructions in each of them. An example usage would be `buildozer -f file_1 -f file_2`. This should be backwards compatible with existing usages. 
It looks like `flag` doesn't support multiple instances of the same flag, so I've implemented a custom solution in `buildozer/main.go` [taken from StackOverflow](https://stackoverflow.com/questions/28322997/how-to-get-a-list-of-values-into-a-flag-in-golang).
=> Allow multiple command files to be passed into buildozer

warn/warn_control_flow.go, warn/warn_control_flow_test.go
Don't warn if a variable is initialized everywhere but in if-branches that end with `break` or `continue`.
=> Fix the uninitialized warning

edit/buildozer.go
Fix bug where "fileModified" is leaking across calls to edit.Buildozer.
This would affect all users of buildozer as a library.
=> Make fileModified local

edit/fix.go
Avoid splitting lines including `"$(location <target>)"` references; this can break variable resolution.
Addresses issue #937.
=> Avoid splitting lines with location references

WARNINGS.md, warn/docs/warnings.textproto, warn/warn_cosmetic_test.go
The urls "docs.bazel.build" were changed automatically by Idea to "warn.docs.bazel.build" when I move the "docs" subpackage into "warn".
=> Fix Bazel docs url

buildifier/README.md
Documents the different gazelle_dependencies required when you use WORKSPACE.bazel instead of WORKSPACE.
The error one gets otherwise is somewhat cryptic.
=> Add WORKSPACE.bazel delta to buildifier config

WARNINGS.md, warn/docs/warnings.textproto, warn/warn.go
It's not clear whether it will be forced to manually load Starlark rules instead of using native rules for android, cc, java, proto, and python. The corresponding warnings are therefore not enabled by default anymore. It's still possible to use them explicitly in buildifier by specifying the required warning categories with the `--warnings` flag, e.g. `--warnings=native-cc,native-java` or `--warnings=+native-android,+native-py` to use all default warnings and some of non-default.
Fixes #923.
=> Disable warnigns about native rules

build/BUILD.bazel, build/lex.go, build/parse.y, build/parse.y.go, build/print.go, build/syntax.go, build/testdata/053.build.golden, build/testdata/053.bzl.golden, build/testdata/053.in, build/utils.go, bzlenv/bzlenv.go, warn/warn_control_flow.go, warn/warn_control_flow_test.go, warn/warn_docstring.go, warn/warn_docstring_test.go, warn/warn_macro.go, warn/warn_macro_test.go, warn/warn_naming.go
The commit allows using Python3-like type annotations for function parameters and return values:
def f(x: int, y: str) -> List[bool]:
pass
Fixes #900
=> Support type annotations

warn/warn_control_flow.go, warn/warn_control_flow_test.go
WORKSPACE files allow load() statements that are not at the top, and the imports can shadow previous ones.
This change restricts the 'symbol already loaded' warning to non-WORKSPACE files.
=> Do not warn about repeated loads in WORKSPACE file

buildozer/buildozer_test.sh, edit/buildozer.go
Only yield suffix and after-comments if they exist.
Fix for #958.
=> Fix backward compatibility of Buildozer API

buildifier/runner.bash.template
=> When buildifier_test rule is ran with `bazel run`, it will run on the WORKSPACE files rather than on the provided srcs.

buildifier/internal/factory.bzl
This commit changes the default value passed to the buildifier tool via
the `-mode` argument from `fix` to `diff` when defining a
`buildifier_test` target. This is necessary, as `fix` attempts to format
the files, which fails due to attempting to open and operator on files
in a read-only sandbox.
Given that `fix` is not an available value for the `mode` attribute to
the `buildifier_test` rule when manually specified, it makes sense to
remove it.
closes #971
=> fix(buildifier): default buildifier_test to "diff" mode

buildifier/internal/factory.bzl
Allow users to specify their own `buildifier` binary in the `buildifier` rule. For example, users can use a pre-build binary that can be download from the github release page. 
Fixes #974
=> renamed attribute in buildifier rule: _buildifier -> buildifier

build/print.go
CommentBlock nodes are no longer special cases for the printer and don't need to be handled separately.
=> Allow FormatString() to work on CommentBlock

buildozer/README.md, buildozer/buildozer_test.sh, edit/buildozer.go, edit/buildozer_command_file_test.go
Fixes for #357.
If a line in the command file includes a '*' as the label, that will
expand to the full list of labels from the command line.
For example with the file `cmd.dozer`
```
remove compatible_with //buildenv/target:foo|*
remove compatible_with //buildenv/target:bar|//other_pkg:*
```
then this invocation
```
buildozer -f cmd.dozer //my_pkg/foo/... //biz/bang:__pkg__
```
would be equivalent to
```
'remove compatible_with //buildenv/target:foo' //my_pkg/foo/... //biz/bang:__pkg__
'remove compatible_with //buildenv/target:bar' //other_pkg:*
```
=> Allow mixing command files with label lists

edit/buildozer.go
Fixes an index error when detecting the buildozer command file syntax `command|*`.
This can occur when a command file is used with no label-list.
=> Bug fix: add size check on split of "cmd|*" syntax.

edit/default_buildifier.go
This might be handy to have around if buildifier needs a custom environment.
=> Add the ability to control env variables for buildifier execution

buildifier/npm/BUILD.bazel, buildozer/npm/BUILD.bazel
We now must explicitly list the substitutions we want to make in the npm package contents, to get the stamp var
Fixes #1002
=> Account for breaking change in rules_nodejs 3.0

build/rewrite.go, build/testdata/024.build.golden, build/testdata/068.build.golden, build/testdata/068.bzl.golden, build/testdata/068.in
Currently buildifer sorts named arguments only when the called function is a literal. This change allows the called function to be any expression, e.g. `foo.bar(a=1,b=2)` or `foo().bar(a=1,b=2)`.
=> Make buildifier sort named arguments of all calls.

buildozer/README.md, edit/buildozer.go
Adds a `path` attribute to the existing `print` command, allow printing of the absolute path the BUILD file that contains the current rule. 
This can be useful when using buildozer's `print` feature to get a lot of data programmatically from BUILD files and using a glob pattern (eg `buildozer 'print srcs deps' //foo:%some_rule`) and it would be useful to get the corresponding file path back to the BUILD file without parsing and calculating it from the label, and taking into account `BUILD.bazel` vs `BUILD` etc.
=> feat(buildozer): add 'path' attr to print command

buildifier/README.md
This updates `buildifier/README.md` to update the setup via Bazel.
This is because when I set up Bazel's WORKSPACE according to the documentation, `bazel build` failed in my M1 Mac Mini (macOS 11.6). It seems rules_go  needs to be updated. Please see the actual error message below.
It seems better to specify the same versions of rules_go, bazel-gazelle, and protobuf as `WORKSPACE`.
Also, I think it is good to specify the release version for buildtools (i.e., buildtools-4.2.0) instead of master.
```
$ uname -v
Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101
$ sw_vers -productVersion
11.6
$ bazel --version
bazel 4.2.1
$ bazel run //:buildifier
DEBUG: Rule 'com_google_protobuf' indicated that a canonical reproducible form can be obtained …
```
=> Update buildifier setup via Bazel

.mailmap
```
This commit adds a .mailmap at the root of the repository in order to
map author names and email addresses to a canonical format (e.g.
combining duplicates, removing non-name strings). When different
email identities existed for the same author, the information from the
most recent commit made by the author was selected.
This plays nicely with `git-shortlog`, and `git-log` with the
`--use-mailmap` option (alternatively, specify `log.mailmap = True` in
your git configuration) [0].
[0]: https://git-scm.com/docs/git-config#Documentation/git-config.txt-logmailmap
```
=> Add mailmap to correct author names and email addresses

build/rewrite.go
Buildifier's linter may add no-op nil nodes to the AST (they may be useful in suggestions). Such nodes should not cause NPEs.
=> Fix panic on nil-nodes

.bazelrc, .gitignore
```
Add support for options specified in `//:.bazelrc.user`
With this change, users can specify options for Bazel in a configuration
file at `//:.bazelrc.user`. The options specified in this file will
be merged with options specified in `//:.bazelrc`. Because this
`//:.bazelrc.user` file is loaded at the end of `//:.bazelrc`, options
specified in the former will override those set in the latter.
```
=> Add support for options specified in `//:.bazelrc.user`

build/lex.go, build/lex_test.go, build/print.go, build/rewrite.go, build/syntax.go, buildifier/integration_test.sh, buildifier/utils/flags.go, buildifier/utils/utils.go, warn/warn_bazel.go, warn/warn_bazel_test.go, warn/warn_control_flow.go, warn/warn_cosmetic.go, warn/warn_test.go
Bazel 5.0 comes with experimental support of MODULE.bazel files, buildifier should support them.
https://docs.bazel.build/versions/5.0.0/bzlmod.html
Fixes #1031
=> Support MODULE.bazel files

buildozer/README.md
```
$ go get github.com/bazelbuild/buildtools/buildozer
go: downloading github.com/bazelbuild/buildtools v0.0.0-20220202150306-c9322a8b4e4b
go: downloading github.com/golang/protobuf v1.4.3
go: downloading google.golang.org/protobuf v1.25.0
go get: installing executables with 'go get' in module mode is deprecated.
Use 'go install pkg@version' instead.
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
Same fix as #1020
=> Update buildozer README.md to use go install

warn/warn_control_flow.go
The break statement is redundant.
=> Address a golint warning

buildozer/README.md
"dict_delete" never existed, so this should just say "dict_remove". I guess no one has fixed this yet because it's so rarely needed.
=> Fix typo in README: dict_delete should be dict_remove.

buildifier/README.md
- 0.29 doesn't work and is no longer current.
- See https://github.com/bazelbuild/rules_go.
=> Updated dep versions in README

buildifier/README.md
on github the comments display as red warnings
=> use jsonc for README

warn/warn_docstring.go, warn/warn_docstring_test.go
Allow the usage of brackets (both square and angled) inside the parentheses used to describe function arguments in docstrings. This allows concise descriptions like
```py
def foo(ctx, files):
"""
Args:
ctx (Context): the Starlark context
files (List<File>): a list of files used to do (...)
mapping (Map[string, int]): a mapping for the (...)
"""
pass
```
I opened https://github.com/bazelbuild/buildtools/issues/916 but no one responded there so I'm just going to open this PR to address that issue and hope I have better luck here
Fixes: https://github.com/bazelbuild/buildtools/issues/916
=> Allow brackets to describe function arguments in docstrings

warn/warn_control_flow.go, warn/warn_control_flow_test.go
In some cases function arguments were reported as not initialized.
=> Fix false positive findings for uninitialized function arguments

build/utils.go, edit/edit.go, warn/warn_control_flow.go, warn/warn_control_flow_test.go
This fix is trying to address the issue of symbols considered unused when imported and used as types only
Example:
```
load(
":f.bzl",
"s1",
"s2",
)
def test(x: s1) -> List[s2]:
pass
```
The PR removes the need for using the `# @unused` directive.
=> Fix symbols considered unused when referenced as types

buildozer/buildozer_test.sh, buildozer/main.go, buildozer/test_common.sh, edit/BUILD.bazel, edit/buildozer.go
Allow users to consume the structured output format in json.
=> buildozer: implement --output_json

build/print.go
`build.FormatString` may be called with nil argument if buildifier is used as a library, it shouldn't crash in such cases.
=> Prevent FormatString from crashing on nil input

build/rewrite.go
Linter may use nil nodes to temporarily apply a fix (e.g. to apply a fix where a function argument is removed, format the file, get the diff and roll the fix back). Temporary fixes expect rewrites to be no-op, however that's not the case with nil-arguments which can be re-sorted differently.
=> Don't sort nil arguments of function calls

unused_deps/README.md
Using `go get github.com/bazelbuild/buildtools/unused_deps` as per the existing documentation, results in:
```
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
replacing it with `go install github.com/bazelbuild/buildtools/unused_deps@latest` works and installs the latest version
Suggesting the change as it could help others.
=> Update README.md with updated installation command

warn/types.go, warn/types_test.go, warn/warn_operation_test.go
This makes the integer division check more accurate when these expressions are involved.
=> Improve type inference for int/float/str/bool(...) expressions

buildozer/README.md, buildozer/buildozer_test.sh, edit/buildozer.go
When e.g. changing a rule type from http_archive to git_repository, it can be useful to remove all attributes before populating new ones.
Effectively this supports "delete and replace", without needing to work out where the replacement rule needs inserting into the file.
=> Support deleting wildcard attrs

buildifier/buildifier.bzl, buildifier/internal/factory.bzl, buildifier/runner.bash.template
This PR addresses #1075 by adding a `no_sandbox` attribute and a WORKSPACE path attribute to`buildifier_test`. Currently, users must explicitly specify every BUILD file they would like to lint in the `srcs` attribute of `buildifier_test`. This PR allows the user to create a test to lint all BUILD files as follows:
```
buildifier_test(
name = "buildifier_check",
diff_command = "diff -u",
mode = "diff",
no_sandbox = True,
workspace = "//:WORKSPACE",
)
```
=> Allow buildifier_test to escape the sandbox

build/rewrite.go, buildifier/integration_test.sh
After refactoring out existing logic to sort string expressions in mixed lists, this logic is reused to sort the positional arguments in `use_repo` calls in chunks delimited by comments. Keyword arguments were already sorted due in the generic call argument sorting pass.
=> Sort and deduplicate `use_repo` positionals 

buildifier/integration_test.sh, tables/tables.go
Since name and version are what uniquely determines a Bazel module, these attributes should be right at the top of both `module` and `bazel_dep` calls. This can also simplify the job of external dependency management tooling (potentially based on regular expressions).
=> Sort `version` right after `name` in `MODULE.bazel`

warn/types.go, warn/types_test.go, warn/warn_bazel_api.go, warn/warn_bazel_operation.go, warn/warn_control_flow.go, warn/warn_operation.go
It can be useful for other analyzers written on top of Buildifier.
=> Make the DetectTypes function public.

build/print.go, buildifier/integration_test.sh, tables/tables.go
Module overrides are grouped together with the `bazel_dep` they override and have their `module_name` argument sorted first.
=> Format module overrides

buildozer/README.md, edit/edit.go
In addition to the pseudo-label syntax for relative file paths (e.g. `WORKSPACE` or `toolchains/BUILD.tpl`), also support absolute labels (e.g. `//WORKSPACE` or `//toolchains/BUILD.tpl`).
Also documents the syntax for files in the README.
Fixes #314
=> Support repo-absolute file paths in buildozer

buildozer/buildozer_test.sh, edit/edit.go
Bazel requires that workspace() declarations come before any loads.
Otherwise buildozer produces WORKSPACE files which fail bazel with the following error:
```
Error in workspace: workspace() function should be used only at the top of the WORKSPACE file
```
=> Add loads after workspace() declarations

WARNINGS.md, warn/docs/warnings.textproto, warn/warn_bazel_api_test.go, wspace/workspace.go, wspace/workspace_test.go
- Stop advising people to use `new_git_repository`
- Fix workspace tests to account for both being equivalent now.
This is only part of the deprecation.  We need an entirely new feature to rewrite new_git_repository as git_repository. I'm leaving that for someone else.  It's not obvious that we should just do it, because then buildifier would only work for bazel >= 6.x. So what we really need is for buildifier to understand bazel versions, or be tracked by LTS.  For now, I am happy to stop advising people to use the deprecated version.
https://github.com/bazelbuild/bazel/issues/16823
=> new_git_repository deprecation.

WORKSPACE, edit/BUILD.bazel, edit/fix.go, edit/fix_test.go
Several places in fix.go called 'PackageDeclaration' instead of 'ExistingPackageDeclaration'. This would add an empty package declaration if none was present.
=> fix fix.go to stop creating empty package() decls.

warn/warn_control_flow.go, warn/warn_control_flow_test.go
https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#unnamed-macro explicitly encourages all macros to have `name` arguments even if they're not used. `unused-variable` shouldn't warn about such parameters.
=> Don't warn about unused 'name' arguments

buildozer/README.md, buildozer/buildozer_test.sh, edit/buildozer.go
I've left open the structure to removing more complex expressions, but trigger an error in all but the more basic cases.  I wasn't sure what sort of behavior this type of command should have in more complex cases.
I generate a comparison function up-front, which does a lot of virtual switching on types as there didn't seem to be a way to genericly compare expressions.  I've used getAttrValueExpr, however, this does make for a little weirdness in trying to handle the case of strings versus identifiers.  The test case with `"True"` versus `True` tries to demonstrate why identifiers are compared to both string and identifiers.
I assume this will seem incomplete in some respects, but I was putting this up for initial feedback on the approach as well as what would be expected in the test …
=> Add remove_if_equal command to buildozer

buildifier/BUILD.bazel, buildifier/buildifier.go, buildifier/config/BUILD.bazel, buildifier/config/config.go, buildifier/config/config_test.go, buildifier/config/validation.go, buildifier/integration_test.sh, buildifier/utils/BUILD.bazel, edit/edit.go, wspace/workspace.go
- Add new package `github.com/bazelbuild/buildtools/buildifier/config`
- Refactor flags from `buildifier.go` into the `Config` struct.
- Refactor `buildifier.go` to use a `type buildifier struct` initialized with a `Config`.
- Move `github.com/bazelbuild/buildtools/buildifier/edit.isFile` to `github.com/bazelbuild/buildtools/buildifier/wspace.IsRegularFile`
- Move `github.com/bazelbuild/buildtools/buildifier/utils.ValidateInputType` to `github.com/bazelbuild/buildtools/buildifier/config.validateInputType` (and similar functions)
- Add new convention of `{WORKSPACE_DIR}/.buildifier.json` where the config file can optionally exist.
- Add new environment variable `BUILDIFIER_CONFIG` that can override location of config file.
- Add new flag `-config` that can specify location of config file. …
=> buildifier(feature): .buildifier.json config file

build/rule.go, build/rule_test.go
Add method to retrieve rule by name from a file pointer, similar to edit#FindRuleByName. This allows access from the file object itself instead of needing an extra package.
=> Add `File#RuleNamed` Method

buildifier/runner.bash.template
Follow up to https://github.com/bazelbuild/buildtools/pull/1092, which doesn't run on macOS 12.x due to missing `realpath`.  This change falls back to `readlink` in that case and errors if neither is available.
Note that this codepath is only used when the `workspace` argument is provided to break out of the test sandbox:
```
buildifier_test(
name = "buildifier-check",
mode = "check",
no_sandbox = True,
workspace = "//:WORKSPACE.bazel",
)
```
=> Improves portability of buildifier_test

buildozer/buildozer_test.sh, edit/fix.go
WORKSPACE files currently allow shadowing loads (see https://github.com/bazelbuild/bazel/issues/17480), i.e. the following is valid:
```starlark
load("//:one.bzl", "fn")
fn()
load("//:two.bzl", "fn")
fn()
```
Currently buildozer removes the second load because the symbol was already loaded. This is incorrect - removing the second load changes the behaviour of this file.
Instead, only delete a load of the last time it was loaded was from the same place.
=> Preserve loads if they're different

build/rewrite.go, build/testdata/070.build.golden, build/testdata/070.bzl.golden, build/testdata/070.in
If buildifier shortens labels within a single list of labels, it should also short them if the value of the argument is a complex statement such as a concatenation of lists, select statements and other nodes.
This is similar to #1143 but focuses on shortening and joining labels rather than sorting them.
=> Shorten labels within complex expressions

buildozer/buildozer_test.sh, edit/buildozer.go, edit/default_buildifier.go, edit/edit.go, edit/safe/buildifier.go
Before this commit, when applying buildozer to e.g. MODULE.bazel file, it would still apply BUILD-specific formatting rules.
Fixes #1125
=> Let buildozer preserve type-specific formatting

config/config.go, edit/buildozer.go, edit/edit.go, edit/edit_test.go, unused_deps/unused_deps.go
External repo targets can be passed as arguments to unused_deps and unused external repo dependencies are detected.
When an external repo BUILD file needs to be edited to remove an unused dependency, the generated buildozer command will need some postprocessing.  The unused_deps utility does not know the file system location of the BUILD file, just its external repo label.
=> Add external repo support to unused_deps.

edit/buildozer.go
WIth #1148 buildozer doesn't force all files to be treated as BUILD files. However for compatibility reasons if the file type is unknown (e.g. it comes via stdin and its name is unknown) it should be still treated as BUILD, not as Default.
=> Treat unknown files as BUILD files

edit/edit.go, unused_deps/unused_deps.go
The method is public and is currently used by many other projects, changing its signature breaks them.
=> Revert the signature of edit.InterpretLabel

warn/warn_control_flow.go, warn/warn_control_flow_test.go
If a variable is not initialized in some execution paths of a function but is a parameter to an inner function, it shouldn't be warned there as uninitialized.
=> Fix false positive for uninitialized variables

buildifier/config/config_test.go
The following buildifier unit test has been flaking in my CI, with symptom:
```bash
$ bazel test //...
INFO: Invocation ID: 0c41e58f-9ab7-4337-9787-aa525e5e80a3
INFO: Analyzed 128 targets (0 packages loaded, 0 targets configured).
INFO: Found 105 targets and 23 test targets...
FAIL: //buildifier/config:go_default_test (see /mnt/ssd0/cache/bazel/_bazel_kiwi/c4dc02d2b3fe20521581445ef560a9ba/execroot/com_github_bazelbuild_buildtools/bazel-out/k8-fastbuild/testlogs/buildifier/config/go_default_test/test.log)
INFO: Elapsed time: 0.987s, Critical Path: 0.93s
INFO: 24 processes: 8 disk cache hit, 24 linux-sandbox.
INFO: Build completed, 1 test FAILED, 24 total actions
//api_proto:api.gen.pb.go_checkshtest                                    PASSED in 0.0s
//build:go_default_test …
```
=> buildifier: Resolve unit test flake in `TestFindConfigPath`

release/github.sh, status.py
Versions in the future will be tagged with `v1.2.3` instead of `1.2.3`, the release scripts should handle them correctly (see #1098).
=> Prepare release scripts for the new tag format

buildozer/README.md, edit/buildozer.go, edit/buildozer_command_file_test.go
`|` in command files can now be escaped like `\|` to prevent Buildozer from splitting the command on them. This allows the use of some more complex regex in `substitute` as well as handling targets and commands that need to contain `|` for other reasons.
As a result of this change double null bytes (`\x00\x00`) is no longer legal in a command string however.
=> Add the ability to escape `|` in command files to Buildozer.

unused_deps/unused_deps.go
rules_jvm uses the label name as is. Account for it when parsing the stamped manifest.
see https://github.com/bazelbuild/rules_jvm_external/blob/eec0b9c5e7e95d5/private/rules/jvm_import.bzl#L21
=> Work with canonical labels

unused_deps/unused_deps.go
A dependency that is marked for removal might contain [exports](https://bazel.build/reference/be/java#java_library.exports). Since exports are treated as if the parent explicitly depended on them, removal of such a dependency can cause issues since the exported dependencies will no longer be available to the parent. 
This PR proposes to fix this by first adding the exports explicitly to the parent's deps before removing the dependency.
=> unused_deps: Add exported dependencies before removing

edit/bzlmod/bzlmod.go, edit/bzlmod/bzlmod_test.go
`use_repo_add` now inserts a `use_repo` call for the correct proxy when none exists. Previously, it added such a call for the last proxy in the module file, whatever that might be.
Originally observed in https://bazelbuild.slack.com/archives/CDBP88Z0D/p1690549451155769?thread_ts=1690507292.465539&cid=CDBP88Z0D
=> Fix `use_repo_add` with no existing `use_repo`

build_proto/BUILD.bazel
naming this: https://github.com/bazelbuild/buildtools/blob/master/build_proto/BUILD.bazel#L22 `go_default_library` is causing issues:
```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
link: package conflict error: github.com/bazelbuild/buildtools/lang: package imports github.com/bazelbuild/buildtools/build_proto
was compiled with: @@gazelle~override~go_deps~com_github_bazelbuild_buildtools//build_proto:build_proto
but was linked with: @@gazelle~override~go_deps~com_github_bazelbuild_buildtools//build_proto:go_default_library
See https://github.com/bazelbuild/rules_go/issues/1877.
```
We should not be calling a `go_proto_library(` `go_default_library` because it prevents adding the alias. See the `api_proto` file as an example: …
=> go_default_library should not be a go_proto_library

WARNINGS.md, buildifier/config/config_test.go, warn/warn.go
I couldn't find any info to why this one wasn't enabled by default already, it seems like a nice organizational rule that can help reduce conflicts when adding and removing loads in high traffic bzl files
=> Enable out-of-order-load by default

buildozer/README.md, buildozer/buildozer_test.sh, edit/buildozer.go
This allows users of buildozer to format files without also having buildifier installed. This was possible previously by making a trivial edit and reverting it, but a dedicated command is cleaner.
Will be used as part of the upcoming `bazel mod tidy` command.
=> Add `format` command to force unconditional formatting

buildifier/npm/BUILD.bazel, buildozer/npm/BUILD.bazel, warn/warn_cosmetic.go, warn/warn_cosmetic_test.go
Paths like "abc/def" should precede "abc-def" (although `-` is smaller than `/` in ASCII).
=> Compare load paths as paths instead of just strings

edit/buildozer.go
Right now, `print_comment` is inconsistent with `print`: `print` returns `MISSING` when it can't find an attribute, but `print_comment` puts nothing in the output field, so callers would have to rely on parsing STDERR to know when this happened.
While I'm here, I'm fixing "a break statement without a target is redundant at the end of a case" warnings from my IDE.
=> Return error `MISSING` when `print_comment` can't find attribute.

bzlenv/bzlenv.go, warn/warn_control_flow_test.go
Fixes https://github.com/bazelbuild/buildtools/issues/1201
As the test added in this commit shows, prior to this commit, the uninitialized check would incorrectly fail when using list unpack assignment, if the same variable is reused later.
This modifies `CollectLValues`, so that it supports list unpack assignments (in addition to tuple, and normal assignments).
Please let me know if there's anything that needs to be added/modified in this change, thanks! 🙏
=> buildifier: fix uninitialised check when using list unpack assignment

warn/warn_cosmetic.go, warn/warn_cosmetic_test.go
Allow `licenses()` and `package_group()` statements appear before `package()` (like it's been implemented before).
=> Fix package-on-top warning

warn/warn_cosmetic.go, warn/warn_cosmetic_test.go
A package declaration may be not at the top of the file if it depends on some variables defined earlier:
VISIBILITY = [...]
package(
...
default_visibility = VISIBILITY,
)
This dependance may also be indirect and it may be hard to determine whether the package declaration can safely be moved on top, and, if so, together with which assignment expressions. To avoid false positive warnings, with this buildifier will just suppress package-on-top warnings in case there's any assignment expression above package declarations. If the visibility scope in the example above has been loaded from another file it wouldn't have cause a similar issue because load statements come before package declarations by design (which is also enforced by other warnings) and loaded symbols are frozen and can't be …
=> Fix false positive warnings for package on top

generatetables/generate_tables.go, lang/tables.gen.go
Update buildozer to account for the renaming the global attribute `applicable_licenses` to `package_metadata`.
The previous code assumed that `applicable_licenses` existed, and used it to set the type for `default_applicable_licenses`.  Now we simply assume that `default_applicable_licenses` and `default_package_metadata` are label lists.
=> Properly handle default_package_metadata attribute.

.bazelrc, WORKSPACE, buildozer/buildozer_test.sh
Fixes https://github.com/bazelbuild/buildtools/issues/1210
=> Fixes build for Windows

edit/fix.go
Moving licenses was disabled (by mistake) in #1223, but there was no decision yet for doing so.
=> Restore moving licenses

file/file.go
These are analogous to the ReadFile variable added in #1062.
=> Add WriteFile and OpenReadFile variables in buildtools/file API.

warn/warn_bazel.go, warn/warn_bazel_test.go
Fixes #1256.
Previously: constant-glob failed to warn when using named argument `include` with a constant pattern.
Now: constant-glob warns when using named argument `include` with a constant pattern or when the first unnamed argument uses a constant pattern.
=> constant-glob validates named include argument

buildozer/buildozer_test.sh, warn/warn_bazel.go
Stop testing the ability to set `licenses` and `distribs` in the `package()` function.
The `distribs` and `licenses` features are being removed from Bazel. Both are obsolete in the `package()` rule.
`distribs` as a top level function will be removed in a near release of Bazel.
`licenses` in `package()` may soon become a no-op.
=> Stop testing the ability to set `licenses` and `distribs` in `package()`

buildifier/internal/factory.bzl
Calling declare_file on windows even if later is overwritten is a problem in windows genereting the following error
```
The following files have no generating action:
buildifier.bash
```
=> Do not declare bash output on windows

buildifier/internal/factory.bzl
This matches with how the corresponding runner.bash.template is referenced.
This should fix #1259
=> Reference runner.bat with local workspace path

edit/bzlmod/bzlmod.go, edit/bzlmod/bzlmod_test.go
Such assignments don't do anything, but we shouldn't crash on them.
Context: https://bazelbuild.slack.com/archives/C014RARENH0/p1712945309438879
=> Fix crash when MODULE.bazel has `foo = bar.baz()`

build/lex.go, buildozer/buildozer_test.sh
After https://github.com/bazelbuild/bazel/pull/22075, these are the files that can be `include()`ed into `MODULE.bazel` files and should be formatted and edited just like them.
Work towards bazelbuild/bazel#22063
=> Add support for `*.MODULE.bazel` files

buildozer/README.md, edit/buildozer.go, edit/buildozer_test.go
This is useful for making modifications at scale, where you only want to replace certain dictionary values. To illustrate, suppose you have a BUILD file containing many targets, some of which use some "old_value" which you wish to replace with "new_value" in a dictionary, and some of which use other values that you don't want to modify:
```
macro(
name = "foo",
macro_values = {
"key": "old_value",
},
)
macro(
name = "bar",
macro_values = {
"key": "neutral_value",
},
)
```
With this new command, these can all be modified like so:
```
buildozer "dict_replace_if_equal macro_values key old_value new_value" //path/to/these/targets:*
```
Resulting in the desired change:
```
macro(
name = "foo",
macro_values = {
"key": "new_value",
},
)
macro(
name = "bar",
macro_values = {
"key": …
```
=> Add dict_replace_if_equal command to buildozer.

README.md, WARNINGS.md, buildifier/README.md, buildifier/integration_test.sh, buildozer/npm/index.js, launcher.js, release/github.sh, unused_deps/README.md, warn/docs/warnings.textproto, warn/warn.go, warn/warn_cosmetic_test.go
This affects Buildtools and Bazel repos and docs.
=> Replace references to 'master' branches with 'main'

edit/edit.go
There are many cases where `BUILD` files are not available locally: Either they are available upstream or in BCR. Consumers of this function often ignore this return value anyways. Setting it to an empty string seems much more plausible then falling through an matching any other unsuitable case.
Related #1287
=> Return empty string when no BUILD file is available in our workspace

warn/warn.go
The set of warnings is something that is changing over time. As scripts tend to hardcode these, they get out of date and we hit this unexpected warning code path. There's little benefit of having a stack trace from this issue. Thus, it's more convenient to just print the error itself and nothing else.
=> Replace log.Fatalf with log.Exitf to avoid spamming stderr.

.bazelci/presubmit.yml
Addressing https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4122#0191e992-f553-4cd2-9b37-319f62073ab6
We probably need to drop support for ubuntu1804 when upgrading Bazel to 8.0
=> Skip ubuntu1804 in downstream testing

warn/warn_bazel_api.go
`fileReader` may be not present if buildifier is called as a library and no file reader is initiated.
=> Fix a potential NPE

build/rule.go
Prior to this change, if a user were to run multiple consecutive commands, including one `set kind` command.
Any command including a line number would fail if referring to the rule with the changed kind.
Example
```
$ cat package/BUILD
foo_lib(
name = "unknown",
deps = [
"path/to/some:dep",
],
)
$ cat commands
set kind bar_lib|package:%1
rename deps new_deps|package:%1
```
```
$ buildozer -f ./commands 
.../package/BUILD: error while executing commands [{[rename deps new_deps]}] on target package:%1: rule '%1' not found
```
```
$buildozer -f ./commands 
fixed .../package/BUILD
$ cat package/BUILD 
bar_lib(
name = "unknown",
new_deps = [
"path/to/some:dep",
],
)
```
=> Updating `set kind` to remember starting line of the rule

build/print.go, buildifier/integration_test.sh
This allows users to separate tags and associated `use_repo` statements into separate groups.
Also use unified diffs in the integration tests since ordinary diffs make it very hard to reason about whitespace.
Before:
```
go_deps = use_extension("//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
use_repo(
go_deps,
"com_github_bazelbuild_buildtools",
)
go_deps.module(name = "foo")
use_repo(go_deps, "foo")
```
After:
```
go_deps = use_extension("//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
use_repo(
go_deps,
"com_github_bazelbuild_buildtools",
)
go_deps.module(name = "foo")
use_repo(go_deps, "foo")
```
=> Break module extension groups after a `use_repo`

build/rule.go
Rules can currently be created with Call.X(Expr) set to nil, which results in the code panicking. Checking for this error and using the type default for position if there is no other value defined.
Fixes bug introduced in #1342
=> Adding nil check for Rule Call Expression

build/rewrite.go, build/testdata/019.build.golden
Fix incorrect rewrites of `@foo//:foo`.  Encountered when renaming `@com_google_re2//:re2` to `@re2//:re2`.
buildifier should leave these as-is since in `@re2//:re2`, the repository is `re2`, the package is the empty string, and the target is `re2`, and it is not correct to assume that repositories have stable names.
https://github.com/bazelbuild/buildtools/issues/1354
=> Keep targets like "@foo//:foo" formatted as-is.

build/rewrite.go, build/testdata/019.build.golden
Reverts bazelbuild/buildtools#1355
The label `@foo` is synonymous with the label `@foo//:foo`, and the label `@@bar` is synonymous with the label `@@bar//:bar`. Especially the former syntax is widely adopted in the community.
=> Revert "Keep targets like "@foo//:foo" formatted as-is."

build/parse.y, build/parse.y.go, warn/warn_control_flow_test.go
Correctly identify expressions using &=, ^=, >>=, <<= as assignment statements when parsing BUILD files.
The Starlark grammar reference (https://github.com/bazelbuild/starlark/blob/master/spec.md#grammar-reference) identifies expressions using all of these as assignment statements, but the parser doesn't include them in the list, probably an old oversight.
This fixes issue #1330.
=> Bug fix. Correctly identify expressions using &=, ^=, >>=, and <<= as assignment statements when parsing BUILD files.

edit/fix.go
Accept True/False literals as well as obsolete 1/0.
Export of an internal change.
=> Fix buildozer fix tests that assume 1/0 for known boolean fields

buildozer/README.md, edit/buildozer.go, edit/buildozer_test.go
- dict_add, dict_set and dict_remove can now be used with keys / values containing "\:" escaped colon characters
- updating existing pipe-escape functionality to reuse same operation
=> Allowing escaped colon character in dict operations

buildozer/README.md, edit/buildozer.go, edit/buildozer_test.go
A buildozer client are looking to execute the commands of buildozer on the content of a build file, in a service environment (without direct access to the file storage). The new function enables this by running the commands without accessing the file system.
=> Adding function to execute Buildozer commands on a single in-memory file

edit/buildozer.go, edit/buildozer_test.go
https://github.com/bazelbuild/buildtools/pull/1361 caused an issue when splitting a string if the character before the split would be a unicode character since the character was inserted using byte offset. New version only modifies string content which is known since it matches the regex separator
=> Fixing unicode string split issue
